unpackaged/main/default/objects/Campaign/fields/zoom_app__Zoom_Webinar__c.field-meta.xml
<CustomField>
    <fullName>zoom_app__Zoom_Webinar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zoom Webinar</label>
    <referenceTo>zoom_app__Zoom_Webinar__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CampaignMember/fields/zoom_app__Is_Registrant__c.field-meta.xml
<CustomField>
    <fullName>zoom_app__Is_Registrant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is_Registrant</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/CampaignMember/fields/zoom_app__isPanelist__c.field-meta.xml
<CustomField>
    <fullName>zoom_app__isPanelist__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isPanelist</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/CampaignMember/fields/zoom_app__join_time__c.field-meta.xml
<CustomField>
    <fullName>zoom_app__join_time__c</fullName>
    <label>Webinar Join Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/CampaignMember/fields/zoom_app__leave_time__c.field-meta.xml
<CustomField>
    <fullName>zoom_app__leave_time__c</fullName>
    <label>Webinar Leave Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/CampaignMember/fields/zoom_app__panelist_Id__c.field-meta.xml
<CustomField>
    <fullName>zoom_app__panelist_Id__c</fullName>
    <label>Panelist Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CampaignMember/fields/zoom_app__Registrant_Id__c.field-meta.xml
<CustomField>
    <fullName>zoom_app__Registrant_Id__c</fullName>
    <label>Registrant Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CampaignMember/fields/zoom_app__Zoom_Webinar_Registrant__c.field-meta.xml
<CustomField>
    <fullName>zoom_app__Zoom_Webinar_Registrant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zoom Webinar Registrant</label>
    <referenceTo>zoom_app__Zoom_Webinar_Registrant__c</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/zoom_app__Zoom_Webinar__c/zoom_app__Zoom_Webinar__c.object-meta.xml
<CustomObject>
    <description>present a Webinar on Zoom Side</description>
    <label>Zoom Webinar</label>
    <nameField>
        <displayFormat>Zoom-Webinar-{0000}</displayFormat>
        <label>Zoom Webinar Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zoom Webinars</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/zoom_app__Zoom_Webinar__c/fields/zoom_app__Actual_End_Time__c.field-meta.xml
<CustomField>
    <fullName>zoom_app__Actual_End_Time__c</fullName>
    <description>The actual end time of this Webinar</description>
    <inlineHelpText>The actual end time of this Webinar</inlineHelpText>
    <label>Actual End Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/zoom_app__Zoom_Webinar_Attendee__c/zoom_app__Zoom_Webinar_Attendee__c.object-meta.xml
<CustomObject>
    <label>Zoom Webinar Attendee</label>
    <nameField>
        <displayFormat>Webinar-Att-{0000}</displayFormat>
        <label>Zoom Webinar Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zoom Webinar Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/zoom_app__Zoom_Webinar_Attendee__c/fields/zoom_app__Join_Time__c.field-meta.xml
<CustomField>
    <fullName>zoom_app__Join_Time__c</fullName>
    <label>Join Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/zoom_app__Zoom_Webinar_Attendee__c/fields/zoom_app__Leave_Time__c.field-meta.xml
<CustomField>
    <fullName>zoom_app__Leave_Time__c</fullName>
    <label>Leave Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/zoom_app__Zoom_Webinar_Attendee__c/fields/zoom_app__Name__c.field-meta.xml
<CustomField>
    <fullName>zoom_app__Name__c</fullName>
    <label>Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/zoom_app__Zoom_Webinar_Attendee__c/fields/zoom_app__User_Email__c.field-meta.xml
<CustomField>
    <fullName>zoom_app__User_Email__c</fullName>
    <label>User Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/zoom_app__Zoom_Webinar_Attendee__c/fields/zoom_app__Zoom_Webinar__c.field-meta.xml
<CustomField>
    <fullName>zoom_app__Zoom_Webinar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zoom Webinar</label>
    <referenceTo>zoom_app__Zoom_Webinar__c</referenceTo>
    <relationshipLabel>Zoom Webinar Attendees</relationshipLabel>
    <relationshipName>Zoom_Webinar_Attendee</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/zoom_app__Zoom_Webinar_Attendee__c/fields/zoom_app__Zoom_Webinar_Panelist__c.field-meta.xml
<CustomField>
    <fullName>zoom_app__Zoom_Webinar_Panelist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zoom Webinar Panelist</label>
    <referenceTo>zoom_app__Zoom_Webinar_Panelist__c</referenceTo>
    <relationshipLabel>Zoom Webinar Attendees</relationshipLabel>
    <relationshipName>Zoom_Webinar_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/zoom_app__Zoom_Webinar_Attendee__c/fields/zoom_app__Zoom_Webinar_Registrant__c.field-meta.xml
<CustomField>
    <fullName>zoom_app__Zoom_Webinar_Registrant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zoom Webinar Registrant</label>
    <referenceTo>zoom_app__Zoom_Webinar_Registrant__c</referenceTo>
    <relationshipName>Zoom_Webina_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/zoom_app__Zoom_Webinar_Panelist__c/zoom_app__Zoom_Webinar_Panelist__c.object-meta.xml
<CustomObject>
    <label>Zoom Webinar Panelist</label>
    <nameField>
        <label>Zoom Panelist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zoom Webinar Panelists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/zoom_app__Zoom_Webinar_Registrant__c/zoom_app__Zoom_Webinar_Registrant__c.object-meta.xml
<CustomObject>
    <label>Zoom Webinar Registrant</label>
    <nameField>
        <displayFormat>Reg-{0000}</displayFormat>
        <label>Zoom Webinar Registrant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zoom Webinar Registrants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/zoom_app__Zoom_Webinar_Registrant__c/fields/zoom_app__First_Name__c.field-meta.xml
<CustomField>
    <fullName>zoom_app__First_Name__c</fullName>
    <label>First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/zoom_app__Zoom_Webinar_Registrant__c/fields/zoom_app__Last_Name__c.field-meta.xml
<CustomField>
    <fullName>zoom_app__Last_Name__c</fullName>
    <label>Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/zoom_app__Zoom_Webinar_Registrant__c/fields/zoom_app__Zoom_Webinar__c.field-meta.xml
<CustomField>
    <fullName>zoom_app__Zoom_Webinar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zoom Webinar</label>
    <referenceTo>zoom_app__Zoom_Webinar__c</referenceTo>
    <relationshipLabel>Zoom Webinar Registrants</relationshipLabel>
    <relationshipName>Zoom_Webinar_Registrants</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/WebinarLeadService.cls
public without sharing class WebinarLeadService {
    public static final Logger LOGGER = LogFactory.create(WebinarLeadService.class);

    public static Lead createLeadFromWebinarAttendee(zoom_app__Zoom_Webinar_Attendee__c attendee) {
        if (!proceedToCreateLead(attendee)) {
            return null;
        }

        Lead newLead = createLead(attendee);
        if (newLead != null) {
            List<zoom_app__Zoom_Webinar__c> webinars = [ SELECT zoom_app__Actual_End_Time__c FROM zoom_app__Zoom_Webinar__c WHERE Id = :attendee.zoom_app__Zoom_Webinar__c];
            if (webinars.size() > 0) {
                zoom_app__Zoom_Webinar__c webinar = webinars[0];
                // Activity date is the day after the webinar.  We'll use the actual end time not the scheduled end time as the attendees are created after the former not the latter. 
                if (webinar.zoom_app__Actual_End_Time__c != null) {
                    Date webinarEndDate = webinar.zoom_app__Actual_End_Time__c.date();
                    createTaskForLead(newLead, 'registered-webinar-attended', webinarEndDate + 1);
                }
            }

            createCampaignMemberForNewLead(attendee, newLead);
        }

        return newLead;
    }

    private static Lead createLead(zoom_app__Zoom_Webinar_Attendee__c attendee) {
        // There is a trigger which will assign the new Lead to an appropriate SDR if the currently assigned owner is the SDR group.
        Group sdrLeadDistribution = [SELECT Id FROM Group WHERE Name = 'SDR Lead Distribution Queue' LIMIT 1];
        
        Lead newLead = new Lead(
            Email = attendee.zoom_app__User_Email__c,
            Company = 'DON\'T KNOW', // Zoom attendee object doesn't have company - required so uses same default as for lead import
            OwnerId = sdrLeadDistribution.Id,
            Status = 'New',
            LeadSource = 'Event'
        );
        setName(newLead, attendee);

        try {
           insert newLead;

           // Retrieve the lead and return that as the owner should have been updated by a trigger on insert
           return [SELECT Id, OwnerId, FirstName, LastName, Email FROM Lead WHERE Id = :newLead.Id];
        } catch(Exception e) {
           LOGGER.info('Unable to create Lead for {0}.  Problem: {1}.', newLead.email, e.getMessage());
           return null;
        }
     }

     private static boolean proceedToCreateLead (zoom_app__Zoom_Webinar_Attendee__c attendee) {
        String email = attendee.zoom_app__User_Email__c;

        // We identify users by email, and need a means of contacting them
        if (String.isBlank(email)) {
            return false;
        }

        // We only want to create leads for attendees who aren't already in our system
        if (existsInSystem(email)) {
            return false;
        }

        return true;
     }

    private static boolean existsInSystem(String email) {
        User existingUser = tryGetExistingUser(email);
        if (existingUser != null) {
            return true;
        }

        Contact existingContact = tryGetExistingContact(email);
        if (existingContact != null) {
            return true;
        }

        Lead existingLead = tryGetExistingLead(email);
        if (existingLead != null) {
            return true;
        }

        return false;
    }

    private static User tryGetExistingUser(String email) {
        List<User> existingUsers = [SELECT Id FROM User WHERE Email = :email LIMIT 1];

        if (existingUsers.size() == 1) {
            return existingUsers.get(0);
        }

        return null;
    }

    private static Contact tryGetExistingContact(String email) {
        List<Contact> existingContacts = [SELECT Id FROM Contact WHERE Email = :email LIMIT 1];

        if (existingContacts.size() == 1) {
            return existingContacts.get(0);
        }

        return null;
    }

    private static Lead tryGetExistingLead(String email) {
        List<Lead> existingLeads = [ SELECT Id FROM Lead WHERE Email = :email LIMIT 1];

        if (existingLeads.size() == 1) {
            return existingLeads.get(0);
        }

        return null;
    }

    private static void createTaskForLead(Lead lead, String subject, Date taskDate) {
        Task task = new Task(
            Subject = subject,
            Status = 'Open',
            Priority = 'Normal',
            WhoId = lead.Id,
            OwnerId = lead.OwnerId,
            ActivityDate = taskDate
        );

        try {
          insert task;
        } catch(Exception e) {
           LOGGER.info('Unable to create Task for {0}.  Problem: {1}.', lead.Email, e.getMessage());
        }       
    }

    private static void setName(Lead lead, zoom_app__Zoom_Webinar_Attendee__c attendee) {
        // For preference Get the name from the registrant if available as that's in the format we need
        // In unit tests accessing via attendee.zoom_app__Zoom_Webinar_Registrant__r didn't work.  It's also unlikely to in the trigger as :
        // > In a trigger, all fields on the triggering object are available, but no fields on related objects are available, so one of the most common  
        // > Trigger patterns involves collecting related record Ids and querying for them separately from the triggering records. 
        // (https://salesforce.stackexchange.com/a/1889 consulted 19th Feb 2021)
        List<zoom_app__Zoom_Webinar_Registrant__c> registrants = [ SELECT zoom_app__First_Name__c, zoom_app__Last_Name__c  FROM zoom_app__Zoom_Webinar_Registrant__c WHERE Id = :attendee.zoom_app__Zoom_Webinar_Registrant__c];
        if (registrants.size() > 0) {
            zoom_app__Zoom_Webinar_Registrant__c registrant = registrants[0];
            if (registrant.zoom_app__Last_Name__c != null) {
                lead.LastName = registrant.zoom_app__Last_Name__c;
                lead.FirstName = registrant.zoom_app__First_Name__c;
                return;
            }
            if (registrant.zoom_app__First_Name__c != null) {
                lead.LastName = registrant.zoom_app__First_Name__c; // LastName is a required field so if we haven't got one use the first name instead
                return;
            }
            return;
        }

        // But if we can't get it from there, try the name info from the attendee instead.
        String name = attendee.zoom_app__Name__c;
        if (String.isBlank(name)) {
            return;
        }

        String[] names = name.split(' ');
        if (names.size() < 2) {
            lead.LastName = name; // Salesforce requires a LastName, so use what we've been given
            return;
        }

        lead.LastName = names[names.size() - 1];
        lead.FirstName = names[0];
    }

    private static void createCampaignMemberForNewLead(zoom_app__Zoom_Webinar_Attendee__c attendee, Lead lead) {
        // WSDL gives relationship as zoom_app__Campaigns__r, so we need to allow for more than one Campaign per webinar
        List<Campaign> campaigns = [ SELECT Id  FROM Campaign WHERE zoom_app__Zoom_Webinar__c = :attendee.zoom_app__Zoom_Webinar__c];
        List<CampaignMember> campaignMembers = new List<CampaignMember>();
        for(Campaign c : campaigns)
        {
            CampaignMember cm = new CampaignMember(
                CampaignId = c.Id,
                LeadId = lead.Id,
                zoom_app__Is_Registrant__c = attendee.zoom_app__Zoom_Webinar_Registrant__c != null,
                zoom_app__Registrant_Id__c = attendee.zoom_app__Zoom_Webinar_Registrant__c,
                zoom_app__Zoom_Webinar_Registrant__c = attendee.zoom_app__Zoom_Webinar_Registrant__c,
                zoom_app__isPanelist__c = attendee.zoom_app__Zoom_Webinar_Panelist__c != null,
                zoom_app__panelist_Id__c = attendee.zoom_app__Zoom_Webinar_Panelist__c,
                zoom_app__join_time__c = attendee.zoom_app__Join_Time__c,
                zoom_app__leave_time__c = attendee.zoom_app__Leave_Time__c
            );
            campaignMembers.add(cm);
        }
        try {
            insert campaignMembers;                
        } catch(Exception e) {
            LOGGER.info('Unable to create CampaignMembers.  Problem: {0}.', e.getMessage());
        }
    }
}