unpackaged/main/default/objects/Campaign/fields/zoom_app__Zoom_Webinar__c.field-meta.xml
<CustomField>
    <fullName>zoom_app__Zoom_Webinar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zoom Webinar</label>
    <referenceTo>zoom_app__Zoom_Webinar__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Email_2__c.field-meta.xml
<CustomField>
    <fullName>Email_2__c</fullName>
    <description>A custom field to store an additional email where this contact may be reached. Note, many Salesforce activities like reporting, campaigns etc will only consider the standard Email field</description>
    <inlineHelpText>A custom field to store an additional email where this contact may be reached. Note, many Salesforce activities like reporting, campaigns etc will only consider the standard Email field</inlineHelpText>
    <label>Email #2</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/zoom_app__Zoom_Webinar__c/zoom_app__Zoom_Webinar__c.object-meta.xml
<CustomObject>
    <description>present a Webinar on Zoom Side</description>
    <label>Zoom Webinar</label>
    <nameField>
        <displayFormat>Zoom-Webinar-{0000}</displayFormat>
        <label>Zoom Webinar Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zoom Webinars</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/zoom_app__Zoom_Webinar__c/fields/zoom_app__Duration__c.field-meta.xml
<CustomField>
    <fullName>zoom_app__Duration__c</fullName>
    <label>Duration in Minutes</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/zoom_app__Zoom_Webinar__c/fields/zoom_app__Start_Time__c.field-meta.xml
<CustomField>
    <fullName>zoom_app__Start_Time__c</fullName>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/zoom_app__Zoom_Webinar__c/fields/zoom_app__Topic__c.field-meta.xml
<CustomField>
    <fullName>zoom_app__Topic__c</fullName>
    <label>Topic</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/zoom_app__Zoom_Webinar_Attendee__c/zoom_app__Zoom_Webinar_Attendee__c.object-meta.xml
<CustomObject>
    <label>Zoom Webinar Attendee</label>
    <nameField>
        <displayFormat>Webinar-Att-{0000}</displayFormat>
        <label>Zoom Webinar Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zoom Webinar Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/zoom_app__Zoom_Webinar_Attendee__c/fields/zoom_app__Duration__c.field-meta.xml
<CustomField>
    <fullName>zoom_app__Duration__c</fullName>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/zoom_app__Zoom_Webinar_Attendee__c/fields/zoom_app__Name__c.field-meta.xml
<CustomField>
    <fullName>zoom_app__Name__c</fullName>
    <label>Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/zoom_app__Zoom_Webinar_Attendee__c/fields/zoom_app__User_Email__c.field-meta.xml
<CustomField>
    <fullName>zoom_app__User_Email__c</fullName>
    <label>User Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/zoom_app__Zoom_Webinar_Attendee__c/fields/zoom_app__Zoom_Webinar__c.field-meta.xml
<CustomField>
    <fullName>zoom_app__Zoom_Webinar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zoom Webinar</label>
    <referenceTo>zoom_app__Zoom_Webinar__c</referenceTo>
    <relationshipLabel>Zoom Webinar Attendees</relationshipLabel>
    <relationshipName>Zoom_Webinar_Attendee</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/TestWebinarAttendeeInformationService.cls
@isTest
private class TestWebinarAttendeeInformationService {
    @isTest
    public static void shouldNotIncludeEventIfEventSubjectIsNotWebinar() {
        WebinarAttendee attendee = createWebinarAttendee();

        Event event = new Event(
            DurationInMinutes = 0,
            ActivityDateTime = DateTime.now(),
            Subject = 'Demo',
            WhatId = attendee.campaign.Id,
            WhoId = attendee.contact.Id,
            Attended__c = false
        );
        insert event;

        List<WebinarAttendeeInformation> attendeeInfo = WebinarAttendeeInformationService.getWebinarAttendeeInformation(new List<zoom_app__Zoom_Webinar_Attendee__c> { attendee.attendee });

        System.assertEquals(1, attendeeInfo.size());
        System.assertEquals(0, attendeeInfo[0].eventRecords.size());
    }

    @isTest
    public static void shouldNotIncludeEventIfContactNotAMatch() {
        WebinarAttendee attendee = createWebinarAttendee();

        Contact anotherContact = new Contact(
            FirstName = 'Firstname',
            LastName = 'Contact',
            Email = 'not.' + attendee.attendee.zoom_app__User_Email__c
        );
        insert anotherContact;

        Event event = new Event(
            DurationInMinutes = 0,
            ActivityDateTime = DateTime.now(),
            Subject = 'Webinar',
            WhatId = attendee.campaign.Id,
            WhoId = anotherContact.Id,
            Attended__c = false
        );
        insert event;

        List<WebinarAttendeeInformation> attendeeInfo = WebinarAttendeeInformationService.getWebinarAttendeeInformation(new List<zoom_app__Zoom_Webinar_Attendee__c> { attendee.attendee });

        System.assertEquals(1, attendeeInfo.size());
        System.assertEquals(0, attendeeInfo[0].eventRecords.size());
    }

    @isTest
    public static void shouldNotIncludeEventIfCampaignIsNotLinkedToAnyWebinar() {
        WebinarAttendee attendee = createWebinarAttendee();

        // break the association between the Campaign and the webinar
        attendee.campaign.zoom_app__Zoom_Webinar__c = null;
        update attendee.campaign;

        Event event = new Event(
            DurationInMinutes = 0,
            ActivityDateTime = DateTime.now(),
            Subject = 'Webinar',
            WhatId = attendee.campaign.Id,
            WhoId = attendee.contact.Id,
            Attended__c = false
        );
        insert event;

        List<WebinarAttendeeInformation> attendeeInfo = WebinarAttendeeInformationService.getWebinarAttendeeInformation(new List<zoom_app__Zoom_Webinar_Attendee__c> { attendee.attendee });

        System.assertEquals(1, attendeeInfo.size());
        System.assertEquals(0, attendeeInfo[0].eventRecords.size());
    }

    @isTest
    public static void shouldNotIncludeEventIfCampaignIsLinkedToAnotherWebinar() {
        WebinarAttendee attendee = createWebinarAttendee();

        zoom_app__Zoom_Webinar__c otherWebinar = new zoom_app__Zoom_Webinar__c();
        otherWebinar.zoom_app__Start_Time__c = DateTime.now() - 10;
        otherWebinar.zoom_app__Duration__c = 10;
        otherWebinar.zoom_app__Topic__c = 'Test 2';
        insert otherWebinar;

        // associate campaign with the other webinar
        attendee.campaign.zoom_app__Zoom_Webinar__c = otherWebinar.Id;
        update attendee.campaign;

        Event event = new Event(
            DurationInMinutes = 0,
            ActivityDateTime = DateTime.now(),
            Subject = 'Webinar',
            WhatId = attendee.campaign.Id,
            WhoId = attendee.contact.Id,
            Attended__c = false
        );
        insert event;

        List<WebinarAttendeeInformation> attendeeInfo = WebinarAttendeeInformationService.getWebinarAttendeeInformation(new List<zoom_app__Zoom_Webinar_Attendee__c> { attendee.attendee });

        System.assertEquals(1, attendeeInfo.size());
        System.assertEquals(0, attendeeInfo[0].eventRecords.size());
    }

    @isTest
    public static void shouldIncludeAllEventsReferencingWebinarCampaigns() {
        WebinarAttendee attendee = createWebinarAttendee();

        Campaign otherCampaign = new Campaign();
        otherCampaign.Name = 'Campaign 2';
        otherCampaign.zoom_app__Zoom_Webinar__c = attendee.attendee.zoom_app__Zoom_Webinar__c;
        insert otherCampaign;

        Event e1 = new Event(
            DurationInMinutes = 0,
            ActivityDateTime = DateTime.now(),
            Subject = 'Webinar',
            WhatId = attendee.campaign.Id,
            WhoId = attendee.contact.Id,
            Attended__c = false
        );
        insert e1;

        Event e2 = new Event(
            DurationInMinutes = 0,
            ActivityDateTime = DateTime.now(),
            Subject = 'Webinar',
            WhatId = otherCampaign.Id,
            WhoId = attendee.contact.Id,
            Attended__c = false
        );
		insert e2;

        List<WebinarAttendeeInformation> attendeeInfo = WebinarAttendeeInformationService.getWebinarAttendeeInformation(new List<zoom_app__Zoom_Webinar_Attendee__c> { attendee.attendee });

        System.assertEquals(1, attendeeInfo.size());
        System.assertEquals(2, attendeeInfo[0].eventRecords.size());
        System.assertEquals(attendee.campaign.Id, attendeeInfo[0].eventRecords[0].WhatId);
        System.assertEquals(otherCampaign.Id, attendeeInfo[0].eventRecords[1].WhatId);
    }

    @isTest
    public static void shouldIncludeEventsForContactsMatchedByOtherEmail() {
        WebinarAttendee attendee = createWebinarAttendee();
        Contact anotherContact = new Contact(
            FirstName = 'Firstname',
            LastName = 'Contact',
            Email = 'not.' + attendee.attendee.zoom_app__User_Email__c,
        	Email_2__c = attendee.attendee.zoom_app__User_Email__c);
        insert anotherContact;

        Event e1 = new Event(
            DurationInMinutes = 0,
            ActivityDateTime = DateTime.now(),
            Subject = 'Webinar',
            WhatId = attendee.campaign.Id,
            WhoId = attendee.contact.Id,
            Attended__c = false
        );
        insert e1;

        Event e2 = new Event(
            DurationInMinutes = 0,
            ActivityDateTime = DateTime.now(),
            Subject = 'Webinar',
            WhatId = attendee.campaign.Id,
            WhoId = anotherContact.Id,
            Attended__c = false
        );
        insert e2;

        List<WebinarAttendeeInformation> attendeeInfo = WebinarAttendeeInformationService.getWebinarAttendeeInformation(new List<zoom_app__Zoom_Webinar_Attendee__c> { attendee.attendee });

        System.assertEquals(1, attendeeInfo.size());
        System.assertEquals(2, attendeeInfo[0].eventRecords.size());
        System.assertEquals(attendee.contact.Id, attendeeInfo[0].eventRecords[0].WhoId);
        System.assertEquals(anotherContact.Id, attendeeInfo[0].eventRecords[1].WhoId);
    }

    private static WebinarAttendee createWebinarAttendee() {
        String email = 'email@example.com';

        zoom_app__Zoom_Webinar__c w = new zoom_app__Zoom_Webinar__c();
        w.zoom_app__Start_Time__c = DateTime.now() - 10;
        w.zoom_app__Duration__c = 10;
        w.zoom_app__Topic__c = 'Test';
        insert w;

        zoom_app__Zoom_Webinar_Attendee__c a = new zoom_app__Zoom_Webinar_Attendee__c();
        a.zoom_app__User_Email__c = email;
        a.zoom_app__Name__c = 'Test';
        a.zoom_app__Zoom_Webinar__c = w.Id;

        Campaign campaign = new Campaign();
        campaign.Name = 'Campaign 1';
        campaign.zoom_app__Zoom_Webinar__c = w.Id;
        insert campaign;

        Contact contact = new Contact(
            FirstName = 'Firstname',
            LastName = 'Contact',
            Email = email
        );
        insert contact;

        WebinarAttendee result = new WebinarAttendee();
        result.attendee = a;
        result.webinar = w;
        result.contact = contact;
        result.campaign = campaign;

        return result;
    }

    private class WebinarAttendee {
        zoom_app__Zoom_Webinar_Attendee__c attendee;
        zoom_app__Zoom_Webinar__c webinar;
        Contact contact;
        Campaign campaign;
    }
}