unpackaged/main/default/objects/Campaign/fields/zoom_app__Zoom_Webinar__c.field-meta.xml
<CustomField>
    <fullName>zoom_app__Zoom_Webinar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zoom Webinar</label>
    <referenceTo>zoom_app__Zoom_Webinar__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/zoom_app__Zoom_Webinar__c/zoom_app__Zoom_Webinar__c.object-meta.xml
<CustomObject>
    <description>present a Webinar on Zoom Side</description>
    <label>Zoom Webinar</label>
    <nameField>
        <displayFormat>Zoom-Webinar-{0000}</displayFormat>
        <label>Zoom Webinar Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zoom Webinars</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/zoom_app__Zoom_Webinar_Attendee__c/zoom_app__Zoom_Webinar_Attendee__c.object-meta.xml
<CustomObject>
    <label>Zoom Webinar Attendee</label>
    <nameField>
        <displayFormat>Webinar-Att-{0000}</displayFormat>
        <label>Zoom Webinar Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zoom Webinar Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/zoom_app__Zoom_Webinar_Attendee__c/fields/zoom_app__Zoom_Webinar__c.field-meta.xml
<CustomField>
    <fullName>zoom_app__Zoom_Webinar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zoom Webinar</label>
    <referenceTo>zoom_app__Zoom_Webinar__c</referenceTo>
    <relationshipLabel>Zoom Webinar Attendees</relationshipLabel>
    <relationshipName>Zoom_Webinar_Attendee</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/zoom_app__Zoom_Webinar_Attendee__c/fields/zoom_app__Zoom_Webinar_Registrant__c.field-meta.xml
<CustomField>
    <fullName>zoom_app__Zoom_Webinar_Registrant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zoom Webinar Registrant</label>
    <referenceTo>zoom_app__Zoom_Webinar_Registrant__c</referenceTo>
    <relationshipName>Zoom_Webina_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/zoom_app__Zoom_Webinar_Registrant__c/zoom_app__Zoom_Webinar_Registrant__c.object-meta.xml
<CustomObject>
    <label>Zoom Webinar Registrant</label>
    <nameField>
        <displayFormat>Reg-{0000}</displayFormat>
        <label>Zoom Webinar Registrant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zoom Webinar Registrants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/zoom_app__Zoom_Webinar_Registrant__c/fields/zoom_app__Zoom_Webinar__c.field-meta.xml
<CustomField>
    <fullName>zoom_app__Zoom_Webinar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zoom Webinar</label>
    <referenceTo>zoom_app__Zoom_Webinar__c</referenceTo>
    <relationshipLabel>Zoom Webinar Registrants</relationshipLabel>
    <relationshipName>Zoom_Webinar_Registrants</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/WebinarAttendeeInformation.cls
public class WebinarAttendeeInformation {
    public User userRecord;
    public Contact contactRecordByPrimaryEmail;
    public Contact contactRecordByOtherEmail;
    public Lead leadRecord;
    public zoom_app__Zoom_Webinar_Attendee__c webinarAttendeeRecord;
    public zoom_app__Zoom_Webinar_Registrant__c webinarRegistrantRecord;
    public zoom_app__Zoom_Webinar__c webinarRecord;
    public List<Campaign> campaignRecords;
    public List<Event> eventRecords;

    @SuppressWarnings('PMD.ExcessiveParameterList')
    public WebinarAttendeeInformation(User user, Contact contactByPrimaryEmail, Contact contactByOtherEmail, Lead lead, zoom_app__Zoom_Webinar_Attendee__c webinarAttendee, zoom_app__Zoom_Webinar_Registrant__c webinarRegistrant, zoom_app__Zoom_Webinar__c webinar, List<Campaign> campaigns, List<Event> events) {
        this.userRecord = user;
        this.contactRecordByPrimaryEmail = contactByPrimaryEmail;
        this.contactRecordByOtherEmail = contactByOtherEmail;
        this.leadRecord = lead;
        this.webinarAttendeeRecord = webinarAttendee;
        this.webinarRegistrantRecord = webinarRegistrant;
        this.webinarRecord = webinar;
        this.campaignRecords = campaigns;
        this.eventRecords = events;
    }
}