unpackaged/main/default/objects/Account/fields/Activated_Partner_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Activated_Partner_Agreement__c</fullName>
    <formula>TODAY() &lt; Activated_Partner_Agreement_End_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Activated Partner Agreement</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Activated_Partner_Agreement_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Activated_Partner_Agreement_End_Date__c</fullName>
    <description>The end date of a currently active contract associated with this Account</description>
    <inlineHelpText>The end date of a currently active contract associated with this Account</inlineHelpText>
    <label>Activated Partner Agreement End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Gearset_Team__c.field-meta.xml
<CustomField>
    <fullName>Gearset_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Gearset Team</label>
    <referenceTo>Gearset_Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Contract Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard Reseller Agreement</fullName>
                <default>true</default>
                <label>Standard Reseller Agreement</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Gearset_Team__c/Gearset_Team__c.object-meta.xml
<CustomObject>
    <label>Gearset Team</label>
    <nameField>
        <label>Gearset Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gearset Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Gearset_Team__c/fields/Gearset_Team_Id__c.field-meta.xml
<CustomField>
    <fullName>Gearset_Team_Id__c</fullName>
    <externalId>true</externalId>
    <label>Gearset Team Id</label>
    <description>The id of the Gearset team, as you might find on the admin site.</description>
    <inlineHelpText>The id of the Gearset team, as you might find on the admin site.</inlineHelpText>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/AccountContractService_Test.cls
@isTest
public class AccountContractService_Test {
    @isTest
    public static void activatedContractShouldUpdateReferencedAccount() {
        Account newAccount = createTestAccount('TestAcc', 'c18aa7fc-0aea-4fba-aace-f003f722c7c7');
        insert newAccount;

        Contract newContract = new Contract();
        newContract.AccountId = newAccount.Id;
        newContract.StartDate = Date.today().addDays(-1);
        newContract.ContractTerm = 1;
        newContract.Contract_Type__c = 'Standard Reseller Agreement';
        newContract.Status = 'Draft';
        insert newContract;

        Contract contract = [SELECT Status, EndDate FROM Contract WHERE Id = :newContract.Id];
        contract.Status = 'Activated';
        update contract;

        Account account = [
            SELECT Activated_Partner_Agreement_End_Date__c, Activated_Partner_Agreement__c
            FROM Account
            WHERE Id = :newAccount.Id
        ];

        System.assertEquals(contract.EndDate, account.Activated_Partner_Agreement_End_Date__c);
        System.assertEquals(true, account.Activated_Partner_Agreement__c);
    }

    @isTest
    public static void draftContractShouldNotUpdateReferencedAccount() {
        Account newAccount = createTestAccount('TestAcc', 'c18aa7fc-0aea-4fba-aace-f003f722c7c7');
        insert newAccount;

        Contract newContract = new Contract();
        newContract.AccountId = newAccount.Id;
        newContract.StartDate = Date.today().addMonths(-5);
        newContract.ContractTerm = 1;
        newContract.Contract_Type__c = 'Standard Reseller Agreement';
        newContract.Status = 'Draft';
        insert newContract;

        Contract contract = [SELECT Status, EndDate FROM Contract WHERE Id = :newContract.Id];
        contract.Status = 'Activated';
        update contract;

        Account account = [
            SELECT Activated_Partner_Agreement_End_Date__c, Activated_Partner_Agreement__c
            FROM Account
            WHERE Id = :newAccount.Id
        ];

        System.assertEquals(contract.EndDate, account.Activated_Partner_Agreement_End_Date__c);
        System.assertEquals(false, account.Activated_Partner_Agreement__c);
    }

    @isTest
    public static void activatedPartnerAgreementShouldBeFalseIfContractHasExpired() {
        Account newAccount = createTestAccount('TestAcc', 'c18aa7fc-0aea-4fba-aace-f003f722c7c7');
        insert newAccount;

        Contract newContract = new Contract();
        newContract.AccountId = newAccount.Id;
        newContract.StartDate = Date.today().addDays(-1);
        newContract.ContractTerm = 1;
        newContract.Contract_Type__c = 'Standard Reseller Agreement';
        newContract.Status = 'Draft';
        insert newContract;

        Contract contract = [SELECT Status, EndDate FROM Contract WHERE Id = :newContract.Id];
        contract.ContractTerm = 2;
        update contract;

        Account account = [
            SELECT Activated_Partner_Agreement_End_Date__c, Activated_Partner_Agreement__c
            FROM Account
            WHERE Id = :newAccount.Id
        ];

        System.assertEquals(null, account.Activated_Partner_Agreement_End_Date__c);
        System.assertEquals(false, account.Activated_Partner_Agreement__c);
    }

    private static Account createTestAccount(String accountName, String teamId) {
        Gearset_Team__c gt = new Gearset_Team__c(Gearset_Team_Id__c = teamId);
        upsert gt;

        Account account = new Account();
        account.Name = accountName;
        account.Gearset_team__c = gt.Id;
        return account;
    }
}