unpackaged/main/default/objects/Account/fields/churn_risk__c.field-meta.xml
<CustomField>
    <fullName>churn_risk__c</fullName>
    <label>Churn Risk</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Churn_Risk_Stage</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Gearset_Team__c.field-meta.xml
<CustomField>
    <fullName>Gearset_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Gearset Team</label>
    <referenceTo>Gearset_Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Contact_Status__c.field-meta.xml
<CustomField>
    <fullName>Contact_Status__c</fullName>
    <description>Where is the prospect is on the customer journey</description>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Contact_Path</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Gearset_Team__c/Gearset_Team__c.object-meta.xml
<CustomObject>
    <label>Gearset Team</label>
    <nameField>
        <label>Gearset Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gearset Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Gearset_Team__c/fields/Gearset_Team_Id__c.field-meta.xml
<CustomField>
    <fullName>Gearset_Team_Id__c</fullName>
    <externalId>true</externalId>
    <label>Gearset Team Id</label>
    <description>The id of the Gearset team, as you might find on the admin site.</description>
    <inlineHelpText>The id of the Gearset team, as you might find on the admin site.</inlineHelpText>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/AP_Contact__c.field-meta.xml
<CustomField>
    <fullName>AP_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>AP Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>AP Contacts</relationshipLabel>
    <relationshipName>AP_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <label>Invoice Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/LicensesAssigned__c.field-meta.xml
<CustomField>
    <fullName>LicensesAssigned__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The licenses have been assigned in the admin site.</description>
    <inlineHelpText>You need to assign the licenses before moving a renewal opportunity to the Invoice Issued stage</inlineHelpText>
    <label>Licenses Assigned</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/MRR_at_renewal__c.field-meta.xml
<CustomField>
    <fullName>MRR_at_renewal__c</fullName>
    <inlineHelpText>The MRR for this opportunity before the renewal was due</inlineHelpText>
    <label>MRR at renewal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <description>Field for AE to paste confirmation of payment. This can be the either the DocuSign envelope ID or the FastSpring ID.</description>
    <inlineHelpText>Before winning the opportunity you need to provide one of the following: 
- For invoices that have been paid please provide the order ID. For example: GEA123123-1231-12312
- For customers who have agreed Net terms, please provide the Docusign envelope ID. Additionally make sure to fill in the payment information of the opportunity and set a task for a Sales Admin to follow up.
https://www.notion.so/gearset/Opportunity-Win-conditions-01b3a911fb4b4e37a098a70f38b4a4e2</inlineHelpText>
    <label>Payment</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Payment_Stage__c.field-meta.xml
<CustomField>
    <fullName>Payment_Stage__c</fullName>
    <label>Payment Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment delayed past current month</fullName>
            </value>
            <value>
                <fullName>Payment issue</fullName>
            </value>
            <value>
                <fullName>Invoice/payment link sent</fullName>
            </value>
            <value>
                <fullName>AP process confirmed</fullName>
            </value>
            <value>
                <fullName>Payment sent</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Seats_at_renewal__c.field-meta.xml
<CustomField>
    <fullName>Seats_at_renewal__c</fullName>
    <inlineHelpText>The number of seats the customer had before renewing</inlineHelpText>
    <label>Seats at renewal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/globalValueSets/Churn_Risk_Stage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Onboarding</fullName>
    </customValue>
    <customValue>
        <fullName>Ramped</fullName>
    </customValue>
    <customValue>
        <fullName>Churn Risk - Attempting Contact</fullName>
    </customValue>
    <customValue>
        <fullName>Churn Risk - In Discussion</fullName>
    </customValue>
    <customValue>
        <fullName>Churned</fullName>
    </customValue>
    <masterLabel>Account Stage</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Contact_Path.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Outreach</fullName>
        <default>true</default>
        <label>Outreach</label>
    </customValue>
    <customValue>
        <fullName>Replied</fullName>
    </customValue>
    <customValue>
        <fullName>Working</fullName>
    </customValue>
    <customValue>
        <fullName>Closed - Converted</fullName>
    </customValue>
    <customValue>
        <fullName>Nurture</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <customValue>
        <fullName>No Response</fullName>
    </customValue>
    <customValue>
        <fullName>Do Not Contact</fullName>
    </customValue>
    <customValue>
        <fullName>Trash</fullName>
        <isActive>false</isActive>
        <label>Trash</label>
    </customValue>
    <customValue>
        <fullName>Recycle</fullName>
        <isActive>false</isActive>
        <label>Recycle</label>
    </customValue>
    <customValue>
        <fullName>Demo booked</fullName>
        <isActive>false</isActive>
        <label>Demo booked</label>
    </customValue>
    <customValue>
        <fullName>Engaged</fullName>
        <isActive>false</isActive>
        <label>Engaged</label>
    </customValue>
    <description>The stages a contact in an account relates to for named accounts.</description>
    <masterLabel>Contact Path</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/PaymentTeamAssignmentService_Test.cls
@isTest
public class PaymentTeamAssignmentService_Test {
    @isTest
    public static void shouldCreateTaskAndAssignSalesWhenOpportunityReachesIssuingInvoiceStage() {
        Opportunity opp = createTestRenewalOpportunity(
            'Opp1',
            'license123',
            'fastspring123',
            'acc1',
            'f4d1a738-e8d8-4c1f-8cb5-8904fef2f076'
        );
        opp.StageName = 'Invoice Issued';
        update opp;

        List<Task> oppTasks = [
            SELECT Id, Subject
            FROM Task
            WHERE WhatId = :opp.Id AND Subject = 'Invoice ready to be sent'
        ];

        System.assertEquals(1, oppTasks.size());

        Task task = oppTasks.get(0);
    }

    @isTest
    public static void shouldCreateTaskAndAssignSalesWhenOpportunityReachesClosedWonStage() {
        Opportunity opp = createTestRenewalOpportunity(
            'Opp1',
            'license123',
            'fastspring123',
            'acc1',
            'f4d1a738-e8d8-4c1f-8cb5-8904fef2f076'
        );

        opp.StageName = 'Closed Won';
        update opp;

        List<Task> oppTasks = [
            SELECT Id, Subject
            FROM Task
            WHERE WhatId = :opp.Id AND Subject = 'Invoice ready to be sent'
        ];

        System.assertEquals(1, oppTasks.size());

        Task task = oppTasks.get(0);
    }

    @isTest
    public static void shouldCorrectlyRoundRobinCreatedOpportunityTask() {
        Opportunity[] testOpps = new Opportunity[] {
            createTestRenewalOpportunity(
                'Opp1',
                'license1',
                'fastspring1',
                'Acc1',
                'f4d1a738-e8d8-4c1f-8cb5-8904fef2f076'
            ),
            createTestRenewalOpportunity(
                'Opp2',
                'license2',
                'fastspring2',
                'Acc2',
                'f4d1a738-e8d8-4c1f-8cb5-8904fef2f077'
            )
        };

        testOpps.get(0).StageName = 'Invoice Issued';
        testOpps.get(1).StageName = 'Invoice Issued';

        update testOpps;

        // verify that task owners are different
        List<Task> oppTasks = [
            SELECT OwnerId
            FROM Task
            WHERE
                Subject = 'Invoice ready to be sent'
                AND (WhatId = :testOpps.get(0).Id
                OR WhatId = :testOpps.get(1).Id)
        ];

        System.assertEquals(2, oppTasks.size());
        System.assertNotEquals(
            oppTasks.get(0),
            oppTasks.get(1),
            'Created tasks have same owners (should have different ones)'
        );
    }

    @isTest
    public static void shouldNotCreateTaskTwiceIfOtherRenewalOpportunityFieldChanged() {
        Opportunity opp = createTestRenewalOpportunity(
            'Opp1',
            'license123',
            'fastspring123',
            'acc1',
            'f4d1a738-e8d8-4c1f-8cb5-8904fef2f076'
        );
        opp.StageName = 'Invoice Issued';
        update opp;

        opp.Name = 'Once in a Lifetime Opportunity';
        update opp;

        List<Task> oppTasks = [
            SELECT Id, Subject
            FROM Task
            WHERE WhatId = :opp.Id AND Subject = 'Invoice ready to be sent'
        ];

        System.assertEquals(1, oppTasks.size(), 'More than one task was created for this opportunity');
    }

    @isTest
    public static void shouldNotCreateTaskTwiceIfRenewalOpportunityStatusChangesTwice() {
        Opportunity opp = createTestRenewalOpportunity(
            'Opp1',
            'license123',
            'fastspring123',
            'acc1',
            'f4d1a738-e8d8-4c1f-8cb5-8904fef2f076'
        );
        opp.StageName = 'Invoice Issued';
        update opp;

        opp.StageName = 'Discovery';
        update opp;

        opp.StageName = 'Invoice Issued';
        update opp;

        List<Task> oppTasks = [
            SELECT Id, Subject
            FROM Task
            WHERE WhatId = :opp.Id AND Subject = 'Invoice ready to be sent'
        ];

        System.assertEquals(1, oppTasks.size(), 'More than one task was created for this opportunity');
    }

    @isTest
    public static void shouldNotCreateTaskAndAssignSalesWhenOpportunityReachesIssuingInvoiceStageWithoutApContactAndInvoiceSpecified() {
        Opportunity opp = createTestRenewalOpportunity(
            'Opp1',
            'license123',
            'fastspring123',
            'acc1',
            'f4d1a738-e8d8-4c1f-8cb5-8904fef2f076'
        );
        opp.StageName = 'Invoice Issued';
        opp.AP_Contact__c = null;
        opp.Invoice_Number__c = '';
        update opp;

        List<Task> oppTasks = [
            SELECT Id, Subject
            FROM Task
            WHERE WhatId = :opp.Id AND Subject = 'Invoice ready to be sent'
        ];

        System.assertEquals(0, oppTasks.size());
    }

    @isTest
    private static void shouldNotCreateTaskIfOpportunityPaymentHasBeenPaid() {
        Opportunity opp = createTestRenewalOpportunity(
            'Opp1',
            'license123',
            'fastspring123',
            'acc1',
            'f4d1a738-e8d8-4c1f-8cb5-8904fef2f076'
        );
        opp.StageName = 'Invoice Issued';
        opp.Payment_Stage__c = 'Paid';
        update opp;

        List<Task> oppTasks = [
            SELECT Id, Subject
            FROM Task
            WHERE WhatId = :opp.Id AND Subject = 'Invoice ready to be sent'
        ];

        System.assertEquals(0, oppTasks.size());
    }

    @SuppressWarnings('PMD.ExcessiveParameterList')
    private static Opportunity createTestRenewalOpportunity(
        String oppName,
        String licenseId,
        String fastspringRef,
        String accountName,
        String teamId
    ) {
        Gearset_Team__c gt = new Gearset_Team__c(Gearset_Team_Id__c = teamId);
        upsert gt;

        Account account = new Account();
        account.churn_risk__c = 'Onboarding';
        account.Name = accountName;
        account.Gearset_team__c = gt.Id;
        insert account;

        account = [SELECT Id, OwnerId FROM Account WHERE Id = :account.Id]; // refetch to get the new owner id

        Contact contact = new Contact(AccountId = account.Id, LastName = 'TestSurname', Contact_Status__c = 'Outreach');
        insert contact;

        List<LicenseRenewalData> renewals = new List<LicenseRenewalData>{
            new LicenseRenewalData(licenseId, 'Pro', 1, fastspringRef)
        };

        List<TeamLicenseRenewal> teamLicenseRenewals = new List<TeamLicenseRenewal>{
            new TeamLicenseRenewal(teamId, renewals)
        };

        List<CreatedRenewalOpportunity> createdRenewalOpportunities = RenewalOpportunityService.createRenewalOpportunities(
            teamLicenseRenewals
        );

        Id newOpportunityId = createdRenewalOpportunities.get(0).opportunityId;

        Opportunity opp = [SELECT LicensesAssigned__c FROM Opportunity WHERE Id = :newOpportunityId];
        opp.Name = oppName;
        opp.Invoice_Number__c = '12345';
        opp.AP_Contact__c = contact.Id;
        opp.LicensesAssigned__c = true;
        opp.Renewal_Date__c = Date.today().addYears(1);
        opp.Amount = 10;
        opp.Payment__c = '36df87f9-c44f-4b6f-86b1-c76e4735906c';
        opp.MRR_at_renewal__c = 100;
        opp.Seats_at_renewal__c = 1;

        return opp;
    }
}