unpackaged/main/default/objects/Account/fields/churn_risk__c.field-meta.xml
<CustomField>
    <fullName>churn_risk__c</fullName>
    <label>Churn Risk</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Churn_Risk_Stage</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Gearset_Team__c.field-meta.xml
<CustomField>
    <fullName>Gearset_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Gearset Team</label>
    <referenceTo>Gearset_Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Gearset_Team__c/Gearset_Team__c.object-meta.xml
<CustomObject>
    <label>Gearset Team</label>
    <nameField>
        <label>Gearset Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gearset Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Gearset_Team__c/fields/Gearset_Team_Id__c.field-meta.xml
<CustomField>
    <fullName>Gearset_Team_Id__c</fullName>
    <externalId>true</externalId>
    <label>Gearset Team Id</label>
    <description>The id of the Gearset team, as you might find on the admin site.</description>
    <inlineHelpText>The id of the Gearset team, as you might find on the admin site.</inlineHelpText>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Expected__c.field-meta.xml
<CustomField>
    <fullName>Expected__c</fullName>
    <description>The billing cycle linked to the opportunity</description>
    <inlineHelpText>Previously the &#39;Payment Expected&#39; menu</inlineHelpText>
    <label>Billing Cycle</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Monthly Rolling</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semi Annual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Biennial</fullName>
            </value>
            <value>
                <fullName>Triennial</fullName>
            </value>
            <value>
                <fullName>Maybe</fullName>
                <isActive>false</isActive>
                <label>Maybe</label>
            </value>
            <value>
                <fullName>Not_Expected</fullName>
                <isActive>false</isActive>
                <label>Not Expected</label>
            </value>
            <value>
                <fullName>Should_Be_Fine</fullName>
                <isActive>false</isActive>
                <label>Should Be Fine</label>
            </value>
            <value>
                <fullName>Yes</fullName>
                <isActive>false</isActive>
                <label>Yes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <description>Field for AE to paste confirmation of payment. This can be the either the DocuSign envelope ID or the FastSpring ID.</description>
    <inlineHelpText>Before winning the opportunity you need to provide one of the following: 
- For invoices that have been paid please provide the order ID. For example: GEA123123-1231-12312
- For customers who have agreed Net terms, please provide the Docusign envelope ID. Additionally make sure to fill in the payment information of the opportunity and set a task for a Sales Admin to follow up.
https://www.notion.so/gearset/Opportunity-Win-conditions-01b3a911fb4b4e37a098a70f38b4a4e2</inlineHelpText>
    <label>Payment</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Churn_Risk_Stage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Onboarding</fullName>
    </customValue>
    <customValue>
        <fullName>Ramped</fullName>
    </customValue>
    <customValue>
        <fullName>Churn Risk - Attempting Contact</fullName>
    </customValue>
    <customValue>
        <fullName>Churn Risk - In Discussion</fullName>
    </customValue>
    <customValue>
        <fullName>Churned</fullName>
    </customValue>
    <masterLabel>Account Stage</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/TestBillingCycleMustBeSetWhenOpIsWon.cls
@isTest
private class TestBillingCycleMustBeSetWhenOpIsWon {
    @isTest
    public static void billingCycleMustBeSetWhenOpIsWon() {
        User u = TestUtils.createStandardUser('Last', 'my@email.com');

        Gearset_team__c t = new Gearset_team__c(
            Gearset_Team_Id__c = '03d25780-ecec-49bd-ab2d-cbe66095e3c0'
        );
        upsert t;

        insert u;
        Account a = new Account(
            Name = 'My account',
            OwnerId = u.Id,
            Churn_risk__c = 'Churn Risk - Attempting Contact',
            Gearset_Team__c = t.Id
        );
        insert a;
        
        Opportunity o = new Opportunity(
            Name = 'My account op',
            StageName = 'Closed Won',
            OwnerId = u.Id,
            AccountId = a.Id,
            CloseDate = Date.today(),
            LeadSource = 'Direct',
            Type = 'New',
            Payment__c = 'GEA210215-1892-66159',
            Expected__c = 'Unknown',
            Amount = 300
        );
        insert o;
        
        Opportunity newOpp = [SELECT Expected__c FROM Opportunity WHERE Id = :o.Id];
        System.assertEquals('Unknown', newOpp.Expected__c);
    }
    
    @isTest
    public static void throwsWhenBillingCycleIsNotSetWhenOpIsWon() {
        User u = TestUtils.createStandardUser('Last', 'my@email.com');

        Gearset_team__c t = new Gearset_team__c(
            Gearset_Team_Id__c = '03d25780-ecec-49bd-ab2d-cbe66095e3c0'
        );
        upsert t;

        insert u;
        Account a = new Account(
            Name = 'My account',
            OwnerId = u.Id,
            Churn_risk__c = 'Churn Risk - Attempting Contact',
            Gearset_Team__c = t.Id
        );
        insert a;
        
        Opportunity o = new Opportunity(
            Name = 'My account op',
            StageName = 'Closed Won',
            OwnerId = u.Id,
            AccountId = a.Id,
            CloseDate = Date.today(),
            LeadSource = 'Direct',
            Type = 'New',
            Payment__c = 'GEA210215-1892-66159',
            Amount = 300
        );
        
        String errorMessage = '';
        try{
            insert o;
        }
        catch(Exception e){
            errorMessage = e.getMessage();
        }
        System.Assert(errorMessage.contains('The opportunity cannot enter Closed Won stage without a Billing Cycle field populated with a value'));
    }
}