unpackaged/main/default/objects/Account/fields/churn_risk__c.field-meta.xml
<CustomField>
    <fullName>churn_risk__c</fullName>
    <label>Churn Risk</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Churn_Risk_Stage</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Gearset_Team__c.field-meta.xml
<CustomField>
    <fullName>Gearset_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Gearset Team</label>
    <referenceTo>Gearset_Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Gearset_Team__c/Gearset_Team__c.object-meta.xml
<CustomObject>
    <label>Gearset Team</label>
    <nameField>
        <label>Gearset Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gearset Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Gearset_Team__c/fields/Gearset_Team_Id__c.field-meta.xml
<CustomField>
    <fullName>Gearset_Team_Id__c</fullName>
    <externalId>true</externalId>
    <label>Gearset Team Id</label>
    <description>The id of the Gearset team, as you might find on the admin site.</description>
    <inlineHelpText>The id of the Gearset team, as you might find on the admin site.</inlineHelpText>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <description>Field for AE to paste confirmation of payment. This can be the either the DocuSign envelope ID or the FastSpring ID.</description>
    <inlineHelpText>Before winning the opportunity you need to provide one of the following: 
- For invoices that have been paid please provide the order ID. For example: GEA123123-1231-12312
- For customers who have agreed Net terms, please provide the Docusign envelope ID. Additionally make sure to fill in the payment information of the opportunity and set a task for a Sales Admin to follow up.
https://www.notion.so/gearset/Opportunity-Win-conditions-01b3a911fb4b4e37a098a70f38b4a4e2</inlineHelpText>
    <label>Payment</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Churn_Risk_Stage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Onboarding</fullName>
    </customValue>
    <customValue>
        <fullName>Ramped</fullName>
    </customValue>
    <customValue>
        <fullName>Churn Risk - Attempting Contact</fullName>
    </customValue>
    <customValue>
        <fullName>Churn Risk - In Discussion</fullName>
    </customValue>
    <customValue>
        <fullName>Churned</fullName>
    </customValue>
    <masterLabel>Account Stage</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/TestCsmAssignment.cls
@isTest
private class TestCsmAssignment {  
    private static UserRole csmRoleId = [SELECT Id FROM UserRole WHERE DeveloperName = 'Customer_Success_Manager'];
    
    private static User getCsmUser() {
        User u = TestUtils.createStandardUser('CSM', 'csm@gearset.com');

        u.UserRoleId = csmRoleId.Id;
        return u;
    }
    
    @isTest
    public static void shouldNotSetOwnerOrChurnRiskIfAlreadySetAndMrrLessThan500() {
        User u = TestUtils.createStandardUser('Last', 'my@email.com');

        Gearset_team__c t = new Gearset_team__c(
            Gearset_Team_Id__c = '03d25780-ecec-49bd-ab2d-cbe66095e3c0'
        );
        upsert t;

        insert u;
        Account a = new Account(
            Name = 'My account',
            OwnerId = u.Id,
            Churn_risk__c = 'Churn Risk - Attempting Contact',
            Gearset_Team__c = t.Id
        );
        insert a;
        
        Opportunity o = new Opportunity(
            Name = 'My account op',
            StageName = 'Closed Won',
            OwnerId = u.Id,
            AccountId = a.Id,
            Amount = 300,
            CloseDate = Date.today(),
            LeadSource = 'Inbound',
            Type = 'New',
            Payment__c = 'GEA210215-1892-66159'
        );
        insert o;
        
        CsmAssignment.handleWonOpportunity(o);
        
        Account updatedAccount = [SELECT OwnerId, Churn_risk__c FROM Account WHERE Id = :a.Id];
        System.assertEquals(a.OwnerId, updatedAccount.OwnerId);
        System.assertEquals('Churn Risk - Attempting Contact', updatedAccount.churn_risk__c);
    }
    
    @isTest
    public static void shouldSetOwnerToACsmIfMrrGreaterThan500AndNotCurrentAssignedToOne() {
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs(thisUser) { // this is needed in order to avoid the MIXED_DML_OPERATION exception
            Gearset_team__c t = new Gearset_team__c(
                Gearset_Team_Id__c = '03d25780-ecec-49bd-ab2d-cbe66095e3c0'
            );
            upsert t;

            User u = TestUtils.createStandardUser('Last', 'my@email.com');
            insert getCsmUser();
            insert u;
            Account a = new Account(
                Name = 'My account',
                OwnerId = u.Id,
                Churn_risk__c = 'Ramped',
                Gearset_Team__c = t.Id
            );
            insert a;
            
            Opportunity o = new Opportunity(
                Name = 'My account op',
                StageName = 'Closed Won',
                OwnerId = u.Id,
                AccountId = a.Id,
                Amount = 3000,
                CloseDate = Date.today(),
                LeadSource = 'Inbound',
                Type = 'New',
                Payment__c = '20B3ECBC-1DA5-4A52-8848-961368E502F5'
            );
            insert o;
            
            CsmAssignment.handleWonOpportunity(o);
            
            Account updatedAccount = [SELECT OwnerId, Churn_risk__c FROM Account WHERE Id = :a.Id];
            System.assertNotEquals(u.Id, updatedAccount.OwnerId);
            System.assertEquals('Ramped', updatedAccount.Churn_risk__c);
        }
    }
     
    @isTest
    public static void shouldDoNothingIfOpIsNotNewBusiness() {
        User u = TestUtils.createStandardUser('Last', 'my@email.com');

        Gearset_team__c t = new Gearset_team__c(
            Gearset_Team_Id__c = '03d25780-ecec-49bd-ab2d-cbe66095e3c0'
        );
        upsert t;

        insert u;
        Account a = new Account(
            Name = 'My account',
            OwnerId = u.Id,
            Churn_risk__c = 'Churn Risk - Attempting Contact',
            Gearset_Team__c = t.Id
        );
        insert a;
        
        Opportunity o = new Opportunity(
            Name = 'My account op',
            StageName = 'Closed Won',
            OwnerId = u.Id,
            AccountId = a.Id,
            Amount = 10000,
            CloseDate = Date.today(),
            LeadSource = 'Inbound',
            Type = 'Renewal',
            Payment__c = 'GEA210215-1892-66159'
        );
        insert o;
        
        CsmAssignment.handleWonOpportunity(o);
        
        Account updatedAccount = [SELECT OwnerId, Churn_risk__c FROM Account WHERE Id = :a.Id];
        System.assertEquals(a.OwnerId, updatedAccount.OwnerId);
        System.assertEquals('Churn Risk - Attempting Contact', updatedAccount.churn_risk__c);
    }
    
    @isTest
    public static void shouldNotModifyAccountOver500MrrIfOwnerIsAlreadyACsm() {
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs(thisUser) { // this is needed in order to avoid the MIXED_DML_OPERATION exception
            User csmUser = getCsmUser();
            insert csmUser;
            User u = TestUtils.createStandardUser('Last', 'my@email.com');
            insert u;

            Gearset_team__c t = new Gearset_team__c(
                Gearset_Team_Id__c = '03d25780-ecec-49bd-ab2d-cbe66095e3c0'
            );
            upsert t;
    
            Account a = new Account(
                Name = 'My account',
                OwnerId = csmUser.Id,
                Churn_risk__c = 'Ramped',
                Gearset_Team__c = t.Id
            );
            insert a;
            
            Opportunity o = new Opportunity(
                Name = 'My account op',
                StageName = 'Closed Won',
                OwnerId = u.Id,
                AccountId = a.Id,
                Amount = 501,
                CloseDate = Date.today(),
                LeadSource = 'Inbound',
                Type = 'New',
                Payment__c = '20B3ECBC-1DA5-4A52-8848-961368E502F5'
            );
            insert o;
            
            CsmAssignment.handleWonOpportunity(o);
            
            Account updatedAccount = [SELECT OwnerId, Churn_risk__c FROM Account WHERE Id = :a.Id];
            System.assertEquals(csmUser.Id, updatedAccount.OwnerId);
            System.assertEquals('Ramped', updatedAccount.Churn_risk__c);
        }
    }
    
    @isTest
    public static void shouldSetAccountOwnerToOpportunityOwnerIfCurrentOwnerIsGearbot() {
        User gearbot = [SELECT Id FROM User WHERE Username LIKE 'gearbot@gearset.com%'];
        User u = TestUtils.createStandardUser('Last', 'my@email.com');
        insert u;

        Gearset_team__c t = new Gearset_team__c(
            Gearset_Team_Id__c = '03d25780-ecec-49bd-ab2d-cbe66095e3c0'
        );
        upsert t;

        Account a = new Account(
            Name = 'My account',
            Gearset_Team__c = t.Id,
            Churn_Risk__c = null,
            OwnerId = gearbot.Id
        );
        insert a;
        
        Opportunity o = new Opportunity(
            Name = 'My account op',
            StageName = 'Closed Won',
            OwnerId = u.Id,
            AccountId = a.Id,
            Amount = 300,
            CloseDate = Date.today(),
            LeadSource = 'Inbound',
            Type = 'New',
            Payment__c = 'GEA210215-1892-66159'
        );
        insert o;
        
        CsmAssignment.handleWonOpportunity(o);
        
        Account updatedAccount = [SELECT OwnerId, Churn_risk__c FROM Account WHERE Id = :a.Id];
        System.assertEquals(u.Id, updatedAccount.OwnerId);
        System.assertEquals(null, updatedAccount.Churn_risk__c);
    }
    
    @isTest
    public static void shouldReturnAccountOwnerIfCurrentOwnerIsNotGearbot() {
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs(thisUser) { // this is needed in order to avoid the MIXED_DML_OPERATION exception
            User standardUser = TestUtils.createStandardUser('Last', 'my@email.com');
            insert standardUser;
            
            Gearset_team__c t = new Gearset_team__c(
                Gearset_Team_Id__c = '03d25780-ecec-49bd-ab2d-cbe66095e3c0'
            );
            upsert t;
            
            Account a = new Account(
                Name = 'Some Account',
                OwnerId = standardUser.Id,
                Gearset_Team__c = t.Id
            );
            
            insert a;
            
            Id assigneeId = CsmAssignment.assigneeForNewRenewalOpp(a);
            
            System.assertEquals(standardUser.Id, assigneeId);
        }
    }
    
    @isTest
    public static void shouldPickACsmIfAccountOwnerIsGearbot() {
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs(thisUser) { // this is needed in order to avoid the MIXED_DML_OPERATION exception
            User gearbot = [SELECT Id FROM User WHERE Username LIKE 'gearbot@gearset.com%'];

            Gearset_team__c t = new Gearset_team__c(
                Gearset_Team_Id__c = '03d25780-ecec-49bd-ab2d-cbe66095e3c0'
            );
            upsert t;
    
            Account a = new Account(
                Name = 'My account',
                OwnerId = gearbot.Id,
                Gearset_Team__c = t.Id
            );
            insert a;
                        
            Id assigneeId = CsmAssignment.assigneeForNewRenewalOpp(a);
            System.assertNotEquals(gearbot.Id, assigneeId);
        }
    }
    
    @isTest
    public static void shouldNotUpdateOppIfPaymentFormatIsIncorrect() {
        User u = TestUtils.createStandardUser('Last', 'my@email.com');

        Gearset_team__c t = new Gearset_team__c(
            Gearset_Team_Id__c = '03d25780-ecec-49bd-ab2d-cbe66095e3c0'
        );
        upsert t;

        insert u;
        Account a = new Account(
            Name = 'My account',
            OwnerId = u.Id,
            Churn_risk__c = 'Churn Risk - Attempting Contact',
            Gearset_Team__c = t.Id
        );
        insert a;
        
        Opportunity o = new Opportunity(
            Name = 'My account op',
            StageName = 'Closed Won',
            OwnerId = u.Id,
            AccountId = a.Id,
            Amount = 300,
            CloseDate = Date.today(),
            LeadSource = 'Inbound',
            Type = 'New',
            Payment__c = 'GEA210215-1892-66159S'
        );
        
        try{
            insert o;
        }
        catch(Exception e){
            System.Assert(e.getMessage().contains('Check that your Payment field is a valid Docusign envelope ID or a Fastspring ID. Note: Fastspring IDs do not have S at the end.'));
        }
    }    
    
    @isTest
    public static void allowLowerCaseDocusignIds() {
        User gearbot = [SELECT Id FROM User WHERE Username LIKE 'gearbot@gearset.com%'];
        User u = TestUtils.createStandardUser('Last', 'my@email.com');
        insert u;

        Gearset_team__c t = new Gearset_team__c(
            Gearset_Team_Id__c = '03d25780-ecec-49bd-ab2d-cbe66095e3c0'
        );
        upsert t;

        Account a = new Account(
            Name = 'My account',
            Gearset_Team__c = t.Id,
            Churn_Risk__c = null,
            OwnerId = gearbot.Id
        );
        insert a;
        
        Opportunity o = new Opportunity(
            Name = 'My account op',
            StageName = 'Closed Won',
            OwnerId = u.Id,
            AccountId = a.Id,
            Amount = 300,
            CloseDate = Date.today(),
            LeadSource = 'Inbound',
            Type = 'New',
            Payment__c = '10211464-d638-4e57-845e-ef1991de52d1'
        );
        insert o;
        
        CsmAssignment.handleWonOpportunity(o);
        
        Account updatedAccount = [SELECT OwnerId, Churn_risk__c FROM Account WHERE Id = :a.Id];
        System.assertEquals(u.Id, updatedAccount.OwnerId);
        System.assertEquals(null, updatedAccount.Churn_risk__c);
    }  
}