unpackaged/main/default/objects/Account/fields/churn_risk__c.field-meta.xml
<CustomField>
    <fullName>churn_risk__c</fullName>
    <label>Churn Risk</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Churn_Risk_Stage</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Gearset_Team__c.field-meta.xml
<CustomField>
    <fullName>Gearset_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Gearset Team</label>
    <referenceTo>Gearset_Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Gearset_Team__c/Gearset_Team__c.object-meta.xml
<CustomObject>
    <label>Gearset Team</label>
    <nameField>
        <label>Gearset Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gearset Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Gearset_Team__c/fields/Gearset_Team_Id__c.field-meta.xml
<CustomField>
    <fullName>Gearset_Team_Id__c</fullName>
    <externalId>true</externalId>
    <label>Gearset Team Id</label>
    <description>The id of the Gearset team, as you might find on the admin site.</description>
    <inlineHelpText>The id of the Gearset team, as you might find on the admin site.</inlineHelpText>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Expected__c.field-meta.xml
<CustomField>
    <fullName>Expected__c</fullName>
    <description>The billing cycle linked to the opportunity</description>
    <inlineHelpText>Previously the &#39;Payment Expected&#39; menu</inlineHelpText>
    <label>Billing Cycle</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Monthly Rolling</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semi Annual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Biennial</fullName>
            </value>
            <value>
                <fullName>Triennial</fullName>
            </value>
            <value>
                <fullName>Maybe</fullName>
                <isActive>false</isActive>
                <label>Maybe</label>
            </value>
            <value>
                <fullName>Not_Expected</fullName>
                <isActive>false</isActive>
                <label>Not Expected</label>
            </value>
            <value>
                <fullName>Should_Be_Fine</fullName>
                <isActive>false</isActive>
                <label>Should Be Fine</label>
            </value>
            <value>
                <fullName>Yes</fullName>
                <isActive>false</isActive>
                <label>Yes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Loss_Reason__c.field-meta.xml
<CustomField>
    <fullName>Loss_Reason__c</fullName>
    <label>Loss Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lost to Competitor</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>No Budget / Lost Funding</fullName>
            </value>
            <value>
                <fullName>No Decision / Non-Responsive</fullName>
            </value>
            <value>
                <fullName>No valid use case</fullName>
            </value>
            <value>
                <fullName>Legal / procurement blocked</fullName>
            </value>
            <value>
                <fullName>Errors</fullName>
            </value>
            <value>
                <fullName>Features missing</fullName>
            </value>
            <value>
                <fullName>Trial solved need so no purchase</fullName>
            </value>
            <value>
                <fullName>Free tier</fullName>
            </value>
            <value>
                <fullName>Churn (UPDATE CHURN SPREADSHEET)</fullName>
            </value>
            <value>
                <fullName>Low probability. Reopen if user signs in</fullName>
            </value>
            <value>
                <fullName>Not ready yet</fullName>
            </value>
            <value>
                <fullName>Coronavirus</fullName>
            </value>
            <value>
                <fullName>Region with low propensity to purchase</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <description>Field for AE to paste confirmation of payment. This can be the either the DocuSign envelope ID or the FastSpring ID.</description>
    <inlineHelpText>Before winning the opportunity you need to provide one of the following: 
- For invoices that have been paid please provide the order ID. For example: GEA123123-1231-12312
- For customers who have agreed Net terms, please provide the Docusign envelope ID. Additionally make sure to fill in the payment information of the opportunity and set a task for a Sales Admin to follow up.
https://www.notion.so/gearset/Opportunity-Win-conditions-01b3a911fb4b4e37a098a70f38b4a4e2</inlineHelpText>
    <label>Payment</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Churn_Risk_Stage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Onboarding</fullName>
    </customValue>
    <customValue>
        <fullName>Ramped</fullName>
    </customValue>
    <customValue>
        <fullName>Churn Risk - Attempting Contact</fullName>
    </customValue>
    <customValue>
        <fullName>Churn Risk - In Discussion</fullName>
    </customValue>
    <customValue>
        <fullName>Churned</fullName>
    </customValue>
    <masterLabel>Account Stage</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/TestCloseDateIsUpdatedWhenOpIsWon.cls
@isTest
private class TestCloseDateIsUpdatedWhenOpIsWon {
    @isTest
    public static void shouldSetOpportunityCloseDateToTodayIfWon() {
        Gearset_Team__c t = new Gearset_Team__c(
            Gearset_Team_Id__c = '1234'
        );
        upsert t;

        Account a = new Account(
            Name = 'Test Account'
        );
        a.Gearset_Team__c = t.Id;
        insert a;

        Opportunity o = new Opportunity(
            Name = 'Test opportunity',
            CloseDate = Date.today().addDays(3),
            StageName = 'Invoice Issued',
            Type = 'New',
            LeadSource = 'Direct',
            AccountId = a.Id,
            Amount = 1001
        );
        insert o;

        o.Payment__c = '20B3ECBC-1DA5-4A52-8848-961368E502F5';      
        o.Expected__c = 'Unknown';
        o.StageName = 'Closed Won';
        a.Churn_Risk__c = 'Ramped';
        update a;
        update o;
        
        Opportunity updatedOp = [SELECT CloseDate FROM Opportunity WHERE Id = :o.Id];
        System.assertEquals(Date.today(), updatedOp.CloseDate);
    }
    
    @isTest
    public static void shouldSetOpportunityCloseDateToTodayIfLost() {
        Opportunity o = new Opportunity(
            Name = 'Test opportunity',
            CloseDate = Date.today().addDays(3),
            StageName = 'Invoice Issued',
            LeadSource = 'Direct',
            Type = 'New'
        );
        insert o;
        
        o.Loss_Reason__c = 'Competitor';
        o.StageName = 'Closed Lost';
        update o;
        
        Opportunity updatedOp = [SELECT CloseDate FROM Opportunity WHERE Id = :o.Id];
        System.assertEquals(Date.today(), updatedOp.CloseDate);
    }
    
    @isTest
    public static void shouldNotSetOpportunityCloseDateIfNotMarkedAsWonOrLost() {
        Date closeDate = Date.today().addDays(3);
        Opportunity o = new Opportunity(
            Name = 'Test opportunity',
            CloseDate = closeDate,
            StageName = 'Approaching Renewal',
            LeadSource = 'Direct',
            Type = 'New'
        );
        insert o;
        
        o.StageName = 'Invoice Issued';
        update o;
        
        Opportunity updatedOp = [SELECT CloseDate FROM Opportunity WHERE Id = :o.Id];
        System.assertEquals(closeDate, updatedOp.CloseDate);
    }
}