unpackaged/main/default/objects/Account/fields/Gearset_Team__c.field-meta.xml
<CustomField>
    <fullName>Gearset_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Gearset Team</label>
    <referenceTo>Gearset_Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Show_Partner_Portal__c.field-meta.xml
<CustomField>
    <fullName>Show_Partner_Portal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Dictates whether the partner portal should be visible for this account.</description>
    <inlineHelpText>Dictates whether the partner portal should be visible for this account.</inlineHelpText>
    <label>Show Partner Portal</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Gearset_Team__c/Gearset_Team__c.object-meta.xml
<CustomObject>
    <label>Gearset Team</label>
    <nameField>
        <label>Gearset Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gearset Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Gearset_Team__c/fields/Gearset_Team_Id__c.field-meta.xml
<CustomField>
    <fullName>Gearset_Team_Id__c</fullName>
    <externalId>true</externalId>
    <label>Gearset Team Id</label>
    <description>The id of the Gearset team, as you might find on the admin site.</description>
    <inlineHelpText>The id of the Gearset team, as you might find on the admin site.</inlineHelpText>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/TestPartnerActivityController.cls
@isTest
private class TestPartnerActivityController {
    @isTest
    public static void shouldCreatePartnerAccountOwnerTask() {
        Gearset_Team__c team = new Gearset_Team__c(Gearset_Team_Id__c = 'Team 1');
        User bobbins = [SELECT Id FROM User WHERE Name = 'Gearbot Bobbins' ];
        insert team;

        Account acct = new Account(
            Name = 'My account',
            Gearset_Team__c = team.Id,
            Type = 'Implementation Partner - Free',
            OwnerId = bobbins.Id,
            Show_Partner_Portal__c = true
        );
        insert acct;
        
        PartnerActivityController.PartnerActivityInfo info = new PartnerActivityController.PartnerActivityInfo();
        info.summary = 'downloaded something';
        info.teamId = 'Team 1';
        
        Boolean success = PartnerActivityController.partnerPortalActivity(info);
        
        System.assert(success);

        List<Task> tasks = 
            [SELECT Subject, Status, Priority, WhatId, OwnerId, Description
             FROM Task];
        
        System.assertEquals('Your partner has visited the partner portal. Is this a good opportunity to interact with them?', tasks[0].Subject);
        System.assertEquals('Open', tasks[0].Status);
        System.assertEquals('Normal', tasks[0].Priority);
        System.assertEquals(acct.Id, tasks[0].WhatId);
        System.assertEquals(bobbins.Id, tasks[0].OwnerId);
        System.assertEquals('Partner activity ' + info.summary + ' needs reviewing', tasks[0].Description);
    }
}