unpackaged/main/default/objects/Account/fields/Gearset_Team__c.field-meta.xml
<CustomField>
    <fullName>Gearset_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Gearset Team</label>
    <referenceTo>Gearset_Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Gearset_Team__c/Gearset_Team__c.object-meta.xml
<CustomObject>
    <label>Gearset Team</label>
    <nameField>
        <label>Gearset Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gearset Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Gearset_Team__c/fields/Gearset_Team_Id__c.field-meta.xml
<CustomField>
    <fullName>Gearset_Team_Id__c</fullName>
    <externalId>true</externalId>
    <label>Gearset Team Id</label>
    <description>The id of the Gearset team, as you might find on the admin site.</description>
    <inlineHelpText>The id of the Gearset team, as you might find on the admin site.</inlineHelpText>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/IsPartnerController.cls
@RestResource(urlMapping='/IsPartner')
global with sharing class IsPartnerController {
    @HttpGet
    global static Boolean isPartner() {
        RestRequest request = RestContext.request;
        
        String teamId = request.params.get('gearset_team_id');
        
        if (String.isBlank(teamId)) {
            return false;
        }
        
        List<Account> partnerAccounts = 
            [SELECT Id 
             FROM Account 
             WHERE Type = 'Implementation Partner' AND Gearset_Team__r.Gearset_Team_Id__c = :teamId LIMIT 1 ];
        
        return !partnerAccounts.isEmpty();
    }
}