unpackaged/main/default/objects/Account/fields/Gearset_Team__c.field-meta.xml
<CustomField>
    <fullName>Gearset_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Gearset Team</label>
    <referenceTo>Gearset_Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Gearset_Team__c/Gearset_Team__c.object-meta.xml
<CustomObject>
    <label>Gearset Team</label>
    <nameField>
        <label>Gearset Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gearset Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Gearset_Team__c/fields/Gearset_Team_Id__c.field-meta.xml
<CustomField>
    <fullName>Gearset_Team_Id__c</fullName>
    <externalId>true</externalId>
    <label>Gearset Team Id</label>
    <description>The id of the Gearset team, as you might find on the admin site.</description>
    <inlineHelpText>The id of the Gearset team, as you might find on the admin site.</inlineHelpText>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Rating__c/Rating__c.object-meta.xml
<CustomObject>
    <description>An internal Gearset rating</description>
    <label>Rating</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Rating Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ratings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Rating__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ratings</relationshipLabel>
    <relationshipName>Ratings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Rating__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Rating__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Ratings</relationshipLabel>
    <relationshipName>Ratings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Rating__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Rating__c/fields/Gearset_Team__c.field-meta.xml
<CustomField>
    <fullName>Gearset_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Gearset Team</label>
    <referenceTo>Gearset_Team__c</referenceTo>
    <relationshipLabel>Ratings</relationshipLabel>
    <relationshipName>Ratings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Rating__c/fields/Rating_Id__c.field-meta.xml
<CustomField>
    <fullName>Rating_Id__c</fullName>
    <externalId>true</externalId>
    <label>Rating Id</label>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Rating__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <label>Score</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Rating_Submitted__e/Rating_Submitted__e.object-meta.xml
<CustomObject>
    <label>Rating Submitted</label>
    <pluralLabel>Ratings Submitted</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Rating_Submitted__e/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Rating_Submitted__e/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <length>26</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Rating_Submitted__e/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Rating_Submitted__e/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>A contact's first name</description>
    <label>FirstName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Rating_Submitted__e/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>A contact&#39;s surname</description>
    <label>LastName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Rating_Submitted__e/fields/Rating_Id__c.field-meta.xml
<CustomField>
    <fullName>Rating_Id__c</fullName>
    <label>Rating Id</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Rating_Submitted__e/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <label>Score</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Rating_Submitted__e/fields/Team_Id__c.field-meta.xml
<CustomField>
    <fullName>Team_Id__c</fullName>
    <label>Team_Id</label>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/RatingSubmittedEventConverterTests.cls
@isTest
private class RatingSubmittedEventConverterTests {
    @isTest
    public static void getItemsFromEventsWithNoEventsShouldReturnEmptyList() {
        List<Rating_Submitted__e> events = new List<Rating_Submitted__e>();
        RatingSubmittedEventConverter converter = new RatingSubmittedEventConverter();
        List<Rating__c> objects = converter.getItemsFromEvents(events);

        System.AssertEquals(0, objects.size());
    }

    @isTest
    public static void getItemsFromEventsWithEventsShouldReturnListOfObjects() {
        List<Rating_Submitted__e> events = new List<Rating_Submitted__e>();
        events.add(
            new Rating_Submitted__e(
                Rating_Id__c = 'Rating 1',
                Team_Id__c = 'Team 1',
                Email__c = 'test1@test.com',
                Comment__c = 'Comment 1',
                Score__c = 8,
                Date__c = '2021-01-18T18:11:09.256Z'
            )
        );
        events.add(
            new Rating_Submitted__e(
                Rating_Id__c = 'Rating 2',
                Team_Id__c = 'Team 2',
                Email__c = 'test2@test.com',
                Comment__c = 'Comment 2',
                Score__c = 2,
                Date__c = '2021-01-18T18:11:09.256Z'
            )
        );
        events.add(
            new Rating_Submitted__e(
                Rating_Id__c = 'Rating 3',
                Team_Id__c = 'Team 1',
                Email__c = 'test3@test.com',
                Comment__c = 'Comment 3',
                Score__c = 10,
                Date__c = '2021-01-18T18:11:09.256Z'
            )
        );

        RatingSubmittedEventConverter converter = new RatingSubmittedEventConverter();
        List<Rating__c> objects = converter.getItemsFromEvents(events);

        System.AssertEquals(3, objects.size());
        System.AssertEquals('Rating 1', objects.get(0).Rating_Id__c);
        System.AssertEquals('Rating 2', objects.get(1).Rating_Id__c);
        System.AssertEquals('Rating 3', objects.get(2).Rating_Id__c);
    }

    @isTest
    public static void getItemsFromEventsWithValidTeamShouldLinkToTeam() {
        Gearset_Team__c team = new Gearset_Team__c(Gearset_Team_Id__c = 'Team 1');
        List<Rating_Submitted__e> events = new List<Rating_Submitted__e>();
        events.add(
            new Rating_Submitted__e(
                Rating_Id__c = 'Rating 1',
                Team_Id__c = team.Gearset_Team_Id__c,
                Email__c = 'test1@test.com',
                Comment__c = 'Comment 1',
                Score__c = 8,
                Date__c = '2021-01-18T18:11:09.256Z'
            )
        );

        insert team;
        RatingSubmittedEventConverter converter = new RatingSubmittedEventConverter();
        List<Rating__c> objects = converter.getItemsFromEvents(events);

        System.AssertEquals(1, objects.size());
        System.AssertEquals(team.Id, objects.get(0).Gearset_Team__c);
    }

    @isTest
    public static void getItemsFromEventsWithValidContactAndAccountShouldLinkToContact() {
        User user = TestUtils.createStandardUser('Bob', 'sales@gearset.com');
        insert user;

        Gearset_Team__c team = new Gearset_Team__c(Gearset_Team_Id__c = 'Team 1');
        insert team;

        Account acct = new Account(
            Name = 'My account',
            Gearset_Team__c = team.Id,
            OwnerId = user.Id
        );
        insert acct;
        
        Contact contact = new Contact(Email = 'test@test.com', AccountId = acct.Id, LastName = 'Last', FirstName = 'First' );
        insert contact;
        
        List<Rating_Submitted__e> events = new List<Rating_Submitted__e>();
        events.add(
            new Rating_Submitted__e(
                Rating_Id__c = 'Rating 1',
                Team_Id__c = 'Team 1',
                Email__c = contact.Email,
                Comment__c = 'Comment 1',
                Score__c = 8,
                Date__c = '2021-01-18T18:11:09.256Z'
            )
        );

        RatingSubmittedEventConverter converter = new RatingSubmittedEventConverter();
        List<Rating__c> objects = converter.getItemsFromEvents(events);

        System.AssertEquals(1, objects.size());
        System.AssertEquals(contact.Id, objects.get(0).Contact__c);
        System.AssertEquals(acct.Id, objects.get(0).Account__c);
    }
    
    @isTest
    public static void getItemsFromEventsWithValidAccountAndNoContactShouldCreateNewContact() {
        User user = TestUtils.createStandardUser('Bob', 'sales@gearset.com');
        insert user;

        Gearset_Team__c team = new Gearset_Team__c(Gearset_Team_Id__c = 'Team 1');
        insert team;

        Account acct = new Account(
            Name = 'My account',
            Gearset_Team__c = team.Id,
            OwnerId = user.Id
        );
        insert acct;

        List<Rating_Submitted__e> events = new List<Rating_Submitted__e>();
        events.add(
            new Rating_Submitted__e(
                Rating_Id__c = 'Rating 1',
                Team_Id__c = 'Team 1',
                Email__c = 'NewlyCreatedContact@test.com',
                Comment__c = 'Comment 1',
                Score__c = 8,
                Date__c = '2021-01-18T18:11:09.256Z',
                FirstName__c = 'First',
                LastName__c = 'Name'
            )
        );
        events.add(
            new Rating_Submitted__e(
                Rating_Id__c = 'Rating 2',
                Team_Id__c = 'Team 1',
                Email__c = 'NewlyCreatedContactEmail@test.com',
                Comment__c = 'Comment 2',
                Score__c = 8,
                Date__c = '2021-01-18T18:11:09.256Z',
                FirstName__c = 'First',
                LastName__c = 'Name'
            )
        );

        RatingSubmittedEventConverter converter = new RatingSubmittedEventConverter();
        List<Rating__c> objects = converter.getItemsFromEvents(events);

        System.AssertEquals(2, objects.size());
        System.assertNotEquals(null, objects.get(0).Contact__c);
        System.AssertEquals(acct.Id, objects.get(0).Account__c);
    }
    
    @isTest
    public static void getItemsFromEventsWithNoAccountAndNoContactShouldReturnRatingWithoutContact() {
        List<Rating_Submitted__e> events = new List<Rating_Submitted__e>();
        events.add(
            new Rating_Submitted__e(
                Rating_Id__c = 'Rating 1',
                Team_Id__c = 'Team 1',
                Email__c = 'NewlyCreatedContact@test.com',
                Comment__c = 'Comment 1',
                Score__c = 8,
                Date__c = '2021-01-18T18:11:09.256Z'
            )
        );

        RatingSubmittedEventConverter converter = new RatingSubmittedEventConverter();
        List<Rating__c> objects = converter.getItemsFromEvents(events);

        System.AssertEquals(1, objects.size());
        System.assertEquals('Rating 1', objects.get(0).Rating_Id__c);
        System.assert(objects.get(0).Contact__c == null);
    }

    @isTest
    public static void getItemsFromEventsWithValidAccountShouldLinkToAccount() {
        User user = TestUtils.createStandardUser('Bob', 'sales@gearset.com');
        insert user;

        Gearset_Team__c team = new Gearset_Team__c(Gearset_Team_Id__c = 'Team 1');
        insert team;

        Account acct = new Account(
            Name = 'My account',
            Gearset_Team__c = team.Id,
            OwnerId = user.Id
        );
        insert acct;

        List<Rating_Submitted__e> events = new List<Rating_Submitted__e>();
        events.add(
            new Rating_Submitted__e(
                Rating_Id__c = 'Rating 1',
                Team_Id__c = 'Team 1',
                Email__c = 'test@example.com',
                Comment__c = 'Comment 1',
                Score__c = 8,
                Date__c = '2021-01-18T18:11:09.256Z',
                FirstName__c = 'First',
                LastName__c = 'Last'
            )
        );

        RatingSubmittedEventConverter converter = new RatingSubmittedEventConverter();
        List<Rating__c> objects = converter.getItemsFromEvents(events);

        System.AssertEquals(1, objects.size());
        System.AssertEquals(acct.Id, objects.get(0).Account__c);
        System.AssertEquals(user.Id, objects.get(0).OwnerId);
    }
}