unpackaged/main/default/objects/Account/fields/Gearset_Team__c.field-meta.xml
<CustomField>
    <fullName>Gearset_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Gearset Team</label>
    <referenceTo>Gearset_Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Gearset_Team__c/Gearset_Team__c.object-meta.xml
<CustomObject>
    <label>Gearset Team</label>
    <nameField>
        <label>Gearset Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gearset Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Gearset_Team__c/fields/Gearset_Team_Id__c.field-meta.xml
<CustomField>
    <fullName>Gearset_Team_Id__c</fullName>
    <externalId>true</externalId>
    <label>Gearset Team Id</label>
    <description>The id of the Gearset team, as you might find on the admin site.</description>
    <inlineHelpText>The id of the Gearset team, as you might find on the admin site.</inlineHelpText>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/AP_Contact__c.field-meta.xml
<CustomField>
    <fullName>AP_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>AP Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>AP Contacts</relationshipLabel>
    <relationshipName>AP_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <label>Invoice Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Payment_Stage__c.field-meta.xml
<CustomField>
    <fullName>Payment_Stage__c</fullName>
    <label>Payment Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment delayed past current month</fullName>
            </value>
            <value>
                <fullName>Payment issue</fullName>
            </value>
            <value>
                <fullName>Invoice/payment link sent</fullName>
            </value>
            <value>
                <fullName>AP process confirmed</fullName>
            </value>
            <value>
                <fullName>Payment sent</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/PaymentTeamAssignmentService.cls
public without sharing class PaymentTeamAssignmentService {
    private static final Logger LOGGER = LogFactory.create(PaymentTeamAssignmentService.class);

    private static final Id[] PAYMENT_TEAM_USER_IDS = getPaymentTeamUserIds();

    private static Id[] getPaymentTeamUserIds() {
        User[] users = [
            SELECT Id
            FROM User
            WHERE UserName LIKE 'katharine@gearset.com.production%' OR UserName LIKE 'joey.fereday@gearset.com.production%'
        ];
        Id[] ids = new List<Id>(users.size());

        for (Integer i = 0; i < users.size(); i++) {
            ids[i] = users.get(i).Id;
        }

        return ids;
    }

    public static void onOpportunityReachInvoiceStageOrBeyond(Opportunity opp) {
        LOGGER.info(
            'Opportunity of ID {0} has reached \'Invoice issued\' stage or later. Creating sales task...',
            opp.Id
        );

        if (opp.AP_Contact__c == null || opp.Invoice_Number__c == '') {
            LOGGER.info(
                'An opportunity of ID {0} does not have \'AP Contact\' or \'Invoice Number\' specified. Ignoring...',
                opp.Id
            );
            return;
        }

        if (opp.Payment_Stage__c == 'Paid') {
            LOGGER.info('An opportunity of ID {0} already has been paid for. Ignoring...', opp.Id);
            return;
        }

        if (checkIfTaskAlreadyExists(opp)) {
            LOGGER.info('Sales task for Opportunity of ID {0} already exists. Skipping...', opp.Id);
            return;
        }

        createAndAssignInvoiceTask(opp);

        LOGGER.info('Opportunity of ID {0} has reached \'Invoice issued\' stage. Creating sales task...DONE', opp.Id);
    }

    private static Boolean checkIfTaskAlreadyExists(Opportunity opp) {
        List<Task> oppTasks = [
            SELECT Id, Subject
            FROM Task
            WHERE WhatId = :opp.Id AND Subject = 'Invoice ready to be sent'
        ];

        return oppTasks.size() > 0;
    }

    private static void createAndAssignInvoiceTask(Opportunity opp) {
        LOGGER.info('Creating a task for Opportunity of ID {0}...', opp.Id);

        String teamId = [SELECT Gearset_Team__c FROM Account WHERE Id = :opp.AccountId LIMIT 1].Gearset_Team__c;
        String gearsetTeamId = '???';
        if (teamId != null) {
            gearsetTeamId = [
                SELECT Gearset_Team_Id__c
                FROM Gearset_Team__c
                WHERE Id IN (SELECT Gearset_Team__c FROM Account WHERE Id = :opp.AccountId)
                LIMIT 1
            ]
            .Gearset_Team_Id__c;
        }

        Task task = new Task(
            Subject = 'Invoice ready to be sent',
            Description = 'Team id: ' + gearsetTeamId,
            Status = 'Open',
            Priority = 'Normal',
            WhatId = opp.Id,
            OwnerId = getNextPaymentTeamUserId(),
            ActivityDate = Date.today()
        );

        insert task;

        LOGGER.info('Creating a task for Opportunity of ID {0}...DONE', opp.Id);
    }

    public static Id getNextPaymentTeamUserId() {
        integer tasksOwned = [SELECT COUNT() FROM Task WHERE Id = :PAYMENT_TEAM_USER_IDS];
        return PAYMENT_TEAM_USER_IDS[Math.mod(tasksOwned, PAYMENT_TEAM_USER_IDS.size())];
    }
}