unpackaged/main/default/objects/Account/fields/Gearset_Team__c.field-meta.xml
<CustomField>
    <fullName>Gearset_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Gearset Team</label>
    <referenceTo>Gearset_Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Gearset_Team__c/Gearset_Team__c.object-meta.xml
<CustomObject>
    <label>Gearset Team</label>
    <nameField>
        <label>Gearset Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gearset Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Gearset_Team__c/fields/Gearset_Team_Id__c.field-meta.xml
<CustomField>
    <fullName>Gearset_Team_Id__c</fullName>
    <externalId>true</externalId>
    <label>Gearset Team Id</label>
    <description>The id of the Gearset team, as you might find on the admin site.</description>
    <inlineHelpText>The id of the Gearset team, as you might find on the admin site.</inlineHelpText>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Rating__c/Rating__c.object-meta.xml
<CustomObject>
    <description>An internal Gearset rating</description>
    <label>Rating</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Rating Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ratings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Rating__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ratings</relationshipLabel>
    <relationshipName>Ratings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Rating__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Rating__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Ratings</relationshipLabel>
    <relationshipName>Ratings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Rating__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Rating__c/fields/Gearset_Team__c.field-meta.xml
<CustomField>
    <fullName>Gearset_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Gearset Team</label>
    <referenceTo>Gearset_Team__c</referenceTo>
    <relationshipLabel>Ratings</relationshipLabel>
    <relationshipName>Ratings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Rating__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Rating__c/fields/Rating_Id__c.field-meta.xml
<CustomField>
    <fullName>Rating_Id__c</fullName>
    <externalId>true</externalId>
    <label>Rating Id</label>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Rating__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <label>Score</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Rating_Submitted__e/Rating_Submitted__e.object-meta.xml
<CustomObject>
    <label>Rating Submitted</label>
    <pluralLabel>Ratings Submitted</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Rating_Submitted__e/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Rating_Submitted__e/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <length>26</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Rating_Submitted__e/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Rating_Submitted__e/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>A contact's first name</description>
    <label>FirstName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Rating_Submitted__e/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>A contact&#39;s surname</description>
    <label>LastName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Rating_Submitted__e/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Rating_Submitted__e/fields/Rating_Id__c.field-meta.xml
<CustomField>
    <fullName>Rating_Id__c</fullName>
    <label>Rating Id</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Rating_Submitted__e/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <label>Score</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Rating_Submitted__e/fields/Team_Id__c.field-meta.xml
<CustomField>
    <fullName>Team_Id__c</fullName>
    <label>Team_Id</label>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/RatingSubmittedEventConverter.cls
public without sharing class RatingSubmittedEventConverter {
    public static final Logger LOGGER = LogFactory.create(RatingSubmittedEventConverter.class);

    public List<Rating__c> getItemsFromEvents(List<Rating_Submitted__e> events) {
        Set<String> emailsToFetch = new Set<String>();
        Set<String> teamsToFetch = new Set<String>();
        for (Rating_Submitted__e event : events) {
            emailsToFetch.add(event.Email__c);
            teamsToFetch.add(event.Team_Id__c);
        }

        List<Contact> fetchedContacts = [SELECT Id, Email FROM Contact WHERE Email IN :emailsToFetch];
        LOGGER.info('Found contacts for ratings submitted: {0}', fetchedContacts.size());

        List<Gearset_Team__c> fetchedTeams = [
            SELECT Id, Gearset_Team_Id__c
            FROM Gearset_Team__c
            WHERE Gearset_Team_Id__c IN :teamsToFetch
        ];
        LOGGER.info('Found teams for ratings submitted: {0}', fetchedTeams.size());

        List<Account> fetchedAccounts = [
            SELECT Id, Gearset_team__r.Gearset_team_id__c, OwnerId
            FROM Account
            WHERE Gearset_team__r.Gearset_team_id__c IN :teamsToFetch
        ];
        LOGGER.info('Found accounts for ratings submitted: {0}', fetchedAccounts.size());

        Map<string, Contact> contactMap = new Map<string, Contact>();
        for (Contact a : fetchedContacts) {
            contactMap.put(a.Email, a);
        }

        Map<string, Gearset_Team__c> teamMap = new Map<string, Gearset_Team__c>();
        for (Gearset_Team__c team : fetchedTeams) {
            teamMap.put(team.Gearset_Team_Id__c, team);
        }

        Map<string, Account> accountMap = new Map<string, Account>();
        for (Account account : fetchedAccounts) {
            accountMap.put(account.Gearset_team__r.Gearset_team_id__c, account);
        }

        List<Rating__c> ratings = new List<Rating__c>();
        List<Contact> newContacts = new List<Contact>();
        Map<string, Rating__c> newContactsRatingMap = new Map<string, Rating__c>();
        for (Rating_Submitted__e event : events) {
            Rating__c item = new Rating__c();
            item.Rating_Id__c = event.Rating_Id__c;
            item.Gearset_Team__c = teamMap.get(event.Team_Id__c)?.Id;
            
            Account account = accountMap.get(event.Team_Id__c);
            Contact contact = contactMap.get(event.Email__c);
            item.Contact__c = contact?.Id;
            
            if (account != null) {
                LOGGER.info('Account exists');
                item.Account__c = account.Id;
                item.OwnerId = account.OwnerId;
                
                if (contact == null) {
                    Contact newContact = generateContactFromEvent(event, account);
                    newContacts.add(newContact);
                    newContactsRatingMap.put(newContact.Email, item);
                }
            }
            
            item.Comment__c = event.Comment__c;
            item.Question__c = event.Question__c;
            item.Score__c = event.Score__c;
            item.Date__c = (DateTime) JSON.deserialize('"' + event.Date__c + '"', DateTime.class);
            ratings.add(item);
        }
        
        insert newContacts;
        
        for (Contact contact : newContacts) {
            Rating__c rating = newContactsRatingMap.get(contact.Email);
            rating.Contact__c = contact.Id;
        }

        return ratings;
    }
    
    private Contact generateContactFromEvent(Rating_Submitted__e event, Account account) {
        LOGGER.info('Creating new contact for account');
        Contact item = new Contact();
        item.FirstName = event.FirstName__c;
        item.LastName = event.LastName__c;
        item.Email = event.Email__c;
        item.AccountId = account.Id;
        item.OwnerId = account.OwnerId;
        return item;
    }
}