unpackaged/main/default/objects/Account/fields/Gearset_Team__c.field-meta.xml
<CustomField>
    <fullName>Gearset_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Gearset Team</label>
    <referenceTo>Gearset_Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Email_2__c.field-meta.xml
<CustomField>
    <fullName>Email_2__c</fullName>
    <description>A custom field to store an additional email where this contact may be reached. Note, many Salesforce activities like reporting, campaigns etc will only consider the standard Email field</description>
    <inlineHelpText>A custom field to store an additional email where this contact may be reached. Note, many Salesforce activities like reporting, campaigns etc will only consider the standard Email field</inlineHelpText>
    <label>Email #2</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Email_3__c.field-meta.xml
<CustomField>
    <fullName>Email_3__c</fullName>
    <description>A custom field to store an additional email where this contact may be reached. Note, many Salesforce activities like reporting, campaigns etc will only consider the standard Email field</description>
    <inlineHelpText>A custom field to store an additional email where this contact may be reached. Note, many Salesforce activities like reporting, campaigns etc will only consider the standard Email field</inlineHelpText>
    <label>Email #3</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Gearset_Team__c/Gearset_Team__c.object-meta.xml
<CustomObject>
    <label>Gearset Team</label>
    <nameField>
        <label>Gearset Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gearset Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Gearset_Team__c/fields/Gearset_Team_Id__c.field-meta.xml
<CustomField>
    <fullName>Gearset_Team_Id__c</fullName>
    <externalId>true</externalId>
    <label>Gearset Team Id</label>
    <description>The id of the Gearset team, as you might find on the admin site.</description>
    <inlineHelpText>The id of the Gearset team, as you might find on the admin site.</inlineHelpText>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Referral_Extra_Details__c.field-meta.xml
<CustomField>
    <fullName>Referral_Extra_Details__c</fullName>
    <label>Referral Extra Details</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Referrer_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Referrer_Company_Name__c</fullName>
    <label>Referrer Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Referrer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Referrer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referrer Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Referrer_Email__c.field-meta.xml
<CustomField>
    <fullName>Referrer_Email__c</fullName>
    <label>Referrer Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Referrer_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Referrer_First_Name__c</fullName>
    <label>Referrer First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Referrer_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Referrer_Last_Name__c</fullName>
    <label>Referrer Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/SI_Partner__c.field-meta.xml
<CustomField>
    <fullName>SI_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SI Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/PartnerLeadController.cls
@RestResource(urlMapping='/PartnerLead')
global with sharing class PartnerLeadController {
    private static final Logger LOGGER = LogFactory.create(PartnerLeadController.class);
    
    @HttpPost
    global static Boolean createPartnerReferralLead(PartnerLeadInfo info) {
        Account partnerAccount = getClosestMatchingPartnerAccount(info);
        Contact partnerContact = getClosestMatchingPartnerContact(info, partnerAccount);
        
        handlePartnerReferralLead(info, partnerAccount, partnerContact);
        
        return true;
    }
    
    global class PartnerLeadInfo {
        global String contactCompanyName;
        global String contactEmail;
        global String contactFirstName;
        global String contactLastName;
        global String referrerCompanyName;
        global String referrerEmail;
        global String referrerFirstName;
        global String referrerLastName;
        global String extraDetails;
        global String teamId;
    }
    
    private static void handlePartnerReferralLead(PartnerLeadInfo info, Account partnerAccount, Contact partnerContact) {
        Lead partnerReferralLead = createPartnerReferralLead(info, partnerAccount, partnerContact);
        
        createTaskForPartnerReferralLead(partnerReferralLead);
    }
    
    private static void createTaskForPartnerReferralLead(Lead partnerReferralLead) {
        Task newLeadTask = new Task(
            Subject = 'Can we get this referral lead to be an opp?',
            Status = 'Open',
            Priority = 'Normal',
            WhoId = partnerReferralLead.Id,
            OwnerId = partnerReferralLead.OwnerId,
            Description = 'Referral Lead ' + partnerReferralLead.Email + ' needs triaging',
            ActivityDate = date.today()
        );
        
        insert newLeadTask;
    }
    
    private static Lead createPartnerReferralLead(PartnerLeadInfo info, Account partnerAccount, Contact partnerContact) {
        Lead newLead = new Lead(
            FirstName = info.contactFirstName,
            LastName = info.contactLastName,
            Email = info.contactEmail,
            Company = info.contactCompanyName,
            OwnerId = getNextOwnerFromRoundRobin(),
            Status = 'New',
            LeadSource = 'Partner',
            Referrer_First_Name__c = info.referrerFirstName,
            Referrer_Last_Name__c = info.referrerLastName,
            Referrer_Email__c = info.referrerEmail,
            Referrer_Company_Name__c = info.referrerCompanyName,
            Referral_Extra_Details__c = info.extraDetails,
            SI_Partner__c = partnerAccount.Id
        );
        
        if (partnerContact != null) {
            newLead.Referrer_Contact__c = partnerContact.Id;
        }
        
        // Want to insert ignoring duplicates, so need to do a little dance
        Database.DMLOptions dml = new Database.DMLOptions();
        dml.DuplicateRuleHeader.AllowSave = true;
        Database.SaveResult sr = Database.Insert(newLead, dml);

        if (!sr.isSuccess()) {
            // not sure the easiest way to throw the correct exception here
            throw new DmlException(sr.getErrors()[0].getMessage());
        }
        
        Lead insertedLead = 
            [SELECT Id, OwnerId, Email
             FROM Lead
             WHERE Id = :newLead.Id];
        
        return insertedLead;
    }
    
    private static Id getNextOwnerFromRoundRobin() {
        Id ownerId = null;
        List<Group> sdrLeadTrackers = [SELECT Id FROM Group WHERE Name = 'SDR Lead Distribution Queue'];
        if (!sdrLeadTrackers.isEmpty()) {
            ownerId = sdrLeadTrackers.get(0).Id;
        }
        return ownerId;
    }
    
    private static Account getClosestMatchingPartnerAccount(PartnerLeadInfo info) {
        List<Account> partnerAccounts = 
            [SELECT Id, Name 
             FROM Account 
             WHERE Type = 'Implementation Partner' AND Gearset_Team__r.Gearset_Team_Id__c = :info.teamId ];
        
        if (partnerAccounts.isEmpty()) {
            LOGGER.info('Unable to get matching SI Account from TeamId {0} to create partner lead.', info.teamId);
            throw new IllegalArgumentException('Could not get matching SI Account from TeamId ' + info.teamId);
        }
        
        for (Account account : partnerAccounts) {
            if (account.Name == info.referrerCompanyName) {
                return account;
            }
        }

        return partnerAccounts[0];
    }
    
    private static Contact getClosestMatchingPartnerContact(PartnerLeadInfo info, Account partnerAccount) {
        List<Contact> partnerContactsWithMatchingEmail =
            [SELECT Id, FirstName, LastName 
             FROM Contact 
             WHERE AccountId = :partnerAccount.Id AND (Email = :info.referrerEmail OR Email_2__c = :info.referrerEmail OR Email_3__c = :info.referrerEmail)];
        
        if (partnerContactsWithMatchingEmail.isEmpty()) {
            return null;
        }
        
        for (Contact contact : partnerContactsWithMatchingEmail) {
            if (contact.FirstName == info.referrerFirstName && contact.LastName == info.referrerLastName) {
                return contact;
            }
        }
        
        return partnerContactsWithMatchingEmail[0];
    }
}