unpackaged/main/default/objects/Account/fields/Gearset_Team__c.field-meta.xml
<CustomField>
    <fullName>Gearset_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Gearset Team</label>
    <referenceTo>Gearset_Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Gearset_Team__c/Gearset_Team__c.object-meta.xml
<CustomObject>
    <label>Gearset Team</label>
    <nameField>
        <label>Gearset Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gearset Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Gearset_Team__c/fields/Gearset_Team_Id__c.field-meta.xml
<CustomField>
    <fullName>Gearset_Team_Id__c</fullName>
    <externalId>true</externalId>
    <label>Gearset Team Id</label>
    <description>The id of the Gearset team, as you might find on the admin site.</description>
    <inlineHelpText>The id of the Gearset team, as you might find on the admin site.</inlineHelpText>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/TestRenewalOpportunityController.cls
@isTest
private class TestRenewalOpportunityController {
    private static final Logger LOGGER = LogFactory.create(TestRenewalOpportunityController.class);

    @isTest
    public static void shouldCreateRenewalOpportunityCorrectly() {        
        String testTeamId = 'f4d1a738-e8d8-4c1f-8cb5-8904fef2f076';

        Gearset_Team__c gt = new Gearset_Team__c(
            Gearset_Team_Id__c = testTeamId
        );
        upsert gt;

        LOGGER.info('Inserted test Gearset_team__c {0}', gt.Id);
        
        Account account = new Account();
        account.Name = 'Gearset';
        account.Gearset_team__c = gt.Id;
        insert account;
        
        RestRequest request = new RestRequest();
        request.requestUri = 'https://instance.salesforce.com/services/apexrest/DataBackupTrialLead/' + testTeamId;
        request.httpMethod = 'POST';
        request.addHeader('Content-Type', 'application/json');
        
        String requestJson = '{' + 
            '"teamRenewals": [{' +
                '"teamId": "' + testTeamId + '",' +
                '"expiringLicenses": [{' +
                    '"licenseId": "abcd",' + 
                    '"licensePlanName": ' + '"Pro",' +
                    '"licenseQuantity": ' + '28,' +
                    '"fastspringReference": ' + '"GEA-123-123-123"' +
                '}]' + 
            '}]' +
        '}';
        
        request.requestBody = Blob.valueOf(requestJson);
        RestContext.request = request;

        RenewalOpportunityController.TeamRenewalsResponse teamRenewalsResponse = RenewalOpportunityController.processRenewal();
        
        RenewalOpportunityController.CreatedRenewalOpportunityResponse renewalOpportunityResponse = teamRenewalsResponse.renewalOpportunities.get(0);

        System.assertEquals(renewalOpportunityResponse.licenseIds.get(0), 'abcd');
    }
}