unpackaged/main/default/objects/Account/fields/Gearset_Team__c.field-meta.xml
<CustomField>
    <fullName>Gearset_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Gearset Team</label>
    <referenceTo>Gearset_Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Gearset_Team__c/Gearset_Team__c.object-meta.xml
<CustomObject>
    <label>Gearset Team</label>
    <nameField>
        <label>Gearset Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gearset Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Gearset_Team__c/fields/Gearset_Team_Id__c.field-meta.xml
<CustomField>
    <fullName>Gearset_Team_Id__c</fullName>
    <externalId>true</externalId>
    <label>Gearset Team Id</label>
    <description>The id of the Gearset team, as you might find on the admin site.</description>
    <inlineHelpText>The id of the Gearset team, as you might find on the admin site.</inlineHelpText>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/TestIsPartnerController.cls
@IsTest
public class TestIsPartnerController {
    @isTest static void testNoTeamIdProvided() {
        RestRequest request = new RestRequest();
        request.requestUri = 'https://instance.salesforce.com/services/apexrest/IsPartner';
        request.httpMethod = 'GET';
        
        RestContext.request = request;
        
        Boolean response = IsPartnerController.isPartner();
        System.assertEquals(false, response);
    }
    
    @isTest static void testNonPartnerTeamId() {
        String teamId = setupNonPartnerAccountWithTeamId();
        
        RestRequest request = new RestRequest();
        request.requestUri = 'https://instance.salesforce.com/services/apexrest/IsPartner';
        request.httpMethod = 'GET';
        
        RestContext.request = request;
        request.addParameter('gearset_team_id', teamId);
        
        Boolean response = IsPartnerController.isPartner();
        System.assertEquals(false, response);
    }
    
    @isTest static void testPartnerTeamId() {
        String teamId = setupPartnerAccountWithTeamId();
        
        RestRequest request = new RestRequest();
        request.requestUri = 'https://instance.salesforce.com/services/apexrest/IsPartner';
        request.httpMethod = 'GET';
        
        RestContext.request = request;
        request.addParameter('gearset_team_id', teamId);
        
        Boolean response = IsPartnerController.isPartner();
        System.assertEquals(true, response);
    }
    
    static string setupNonPartnerAccountWithTeamId() {
        Gearset_Team__c team = new Gearset_Team__c(
            Gearset_Team_Id__c = 'test team id', 
            Name = 'test team'
        );
        
        insert team;
        
        Account nonPartnerAccount = new Account(
        	Name = 'Non Partner 1 With Team Id',
            Gearset_Team__c = team.Id
        );
        
        insert nonPartnerAccount;
        
        return team.Gearset_Team_Id__c;
    }
    
    static string setupPartnerAccountWithTeamId() {
        Gearset_Team__c team = new Gearset_Team__c(
            Gearset_Team_Id__c = 'test team id', 
            Name = 'test team'
        );
        
        insert team;
        
        Account partnerAccount = new Account(
        	Name = 'Partner 1 With Team Id',
            Type = 'Implementation Partner',
            Gearset_Team__c = team.Id
        );
        
        insert partnerAccount;
        
        return team.Gearset_Team_Id__c;
    }
}