unpackaged/main/default/objects/Account/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <description>Calculate the region based off the country the user signed up from.</description>
    <formula>CASE(1,
IF (ISBLANK(TEXT(Sign_in_Country__c)), 1, 0), &quot;&quot;,
IF (CONTAINS($Label.Countries_Region_AMER, TEXT(Sign_in_Country__c) + &quot;;&quot;), 1, 0), &quot;AMER&quot;,
IF (CONTAINS($Label.Countries_Region_EMEA, TEXT(Sign_in_Country__c) + &quot;;&quot;), 1, 0), &quot;EMEA&quot;,
IF (CONTAINS($Label.Countries_Region_APAC, TEXT(Sign_in_Country__c) + &quot;;&quot;), 1, 0), &quot;APAC&quot;,
IF (CONTAINS($Label.Countries_Region_Other, TEXT(Sign_in_Country__c) + &quot;;&quot;), 1, 0), &quot;Other&quot;,
&quot;Unknown&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Calculate the region based off the country the user signed up from.</inlineHelpText>
    <label>Sales Region</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sign_in_Country__c.field-meta.xml
<CustomField>
    <fullName>Sign_in_Country__c</fullName>
    <description>The country retrieved from the lead&#39;s IP address when they sign-up, converted from the lead.</description>
    <inlineHelpText>The country retrieved from the lead&#39;s IP address when they sign-up, converted from the lead.</inlineHelpText>
    <label>Sign-in Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unknown</fullName>
                <default>true</default>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <description>Calculate the region based off the country the user signed up from.</description>
    <formula>CASE(1,
IF (ISBLANK(TEXT(Sign_In_Country__c)), 1, 0), &quot;&quot;,
IF (CONTAINS($Label.Countries_Region_AMER, TEXT(Sign_In_Country__c) + &quot;;&quot;), 1, 0), &quot;AMER&quot;,
IF (CONTAINS($Label.Countries_Region_EMEA, TEXT(Sign_In_Country__c) + &quot;;&quot;), 1, 0), &quot;EMEA&quot;,
IF (CONTAINS($Label.Countries_Region_APAC, TEXT(Sign_In_Country__c) + &quot;;&quot;), 1, 0), &quot;APAC&quot;,
IF (CONTAINS($Label.Countries_Region_Other, TEXT(Sign_In_Country__c) + &quot;;&quot;), 1, 0), &quot;Other&quot;,
&quot;Unknown&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Calculate the region based off the country the user signed up from.</inlineHelpText>
    <label>Sales Region</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Sign_In_Country__c.field-meta.xml
<CustomField>
    <fullName>Sign_In_Country__c</fullName>
    <description>The country retrieved from the lead&#39;s IP address when they sign-up. It is set when a user account is first created and updated in the scenario where a user account is updated when logging in to the Gearset app.</description>
    <inlineHelpText>The country retrieved from the lead&#39;s IP address when they sign-up. It is set when a user account is first created and updated in the scenario where a user account is updated when logging in to the Gearset app.</inlineHelpText>
    <label>Sign-In Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unknown</fullName>
                <default>true</default>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/SalesRegionFormulaFieldTests.cls
@isTest
private class SalesRegionFormulaFieldTests {
    private static Account createAccountWithCountry(string country) {
        return new Account
        (
            Name = TestUtils.generateRandomString(10),
            Sign_In_Country__c = country
        );
    }
    
    private static Lead createLeadWithCountry(string country) {
        return new Lead
        (
            LastName = TestUtils.generateRandomString(10),
            Company = 'Gearset',
            Sign_In_Country__c = country
        );
    }
    
    @isTest 
    public static void shouldCorrectlyCalculateAmerRegion(){
        final string country = 'United States';
        Lead lead = createLeadWithCountry(country);
        insert lead;
        Account account = createAccountWithCountry(country);
        insert account;
        
        List<Lead> leads = [SELECT Id, Sales_Region__c FROM Lead];
        List<Account> accounts = [SELECT Id, Sales_Region__c FROM Account];
        
        System.assertEquals(1, leads.size());
        System.assertEquals('AMER', leads.get(0).Sales_Region__c, 'The lead region field returned an unexpected value');
        System.assertEquals(1, accounts.size());
        System.assertEquals('AMER', accounts.get(0).Sales_Region__c, 'The account region field returned an unexpected value');
    }
    
    @isTest 
    public static void shouldCorrectlyCalculateEmeaRegion(){
        final string country = 'United Kingdom';
        Lead lead = createLeadWithCountry(country);
        insert lead;
        Account account = createAccountWithCountry(country);
        insert account;
        
        List<Lead> leads = [SELECT Id, Sales_Region__c FROM Lead];
        List<Account> accounts = [SELECT Id, Sales_Region__c FROM Account];
        
        System.assertEquals(1, leads.size());
        System.assertEquals('EMEA', leads.get(0).Sales_Region__c, 'The lead region field returned an unexpected value');
        System.assertEquals(1, accounts.size());
        System.assertEquals('EMEA', accounts.get(0).Sales_Region__c, 'The account region field returned an unexpected value');
    }
    
    @isTest 
    public static void shouldCorrectlyCalculateApacRegion(){
        final string country = 'Australia';
        Lead lead = createLeadWithCountry(country);
        insert lead;
        Account account = createAccountWithCountry(country);
        insert account;
        
        List<Lead> leads = [SELECT Id, Sales_Region__c FROM Lead];
        List<Account> accounts = [SELECT Id, Sales_Region__c FROM Account];
        
        System.assertEquals(1, leads.size());
        System.assertEquals('APAC', leads.get(0).Sales_Region__c, 'The lead region field returned an unexpected value');
        System.assertEquals(1, accounts.size());
        System.assertEquals('APAC', accounts.get(0).Sales_Region__c, 'The account region field returned an unexpected value');
    }
    
    @isTest 
    public static void shouldCorrectlyCalculateOtherRegion(){
        final string country = 'Brazil';
        Lead lead = createLeadWithCountry(country);
        insert lead;
        Account account = createAccountWithCountry(country);
        insert account;
        
        List<Lead> leads = [SELECT Id, Sales_Region__c FROM Lead];
        List<Account> accounts = [SELECT Id, Sales_Region__c FROM Account];
        
        System.assertEquals(1, leads.size());
        System.assertEquals('Other', leads.get(0).Sales_Region__c, 'The lead region field returned an unexpected value');
        System.assertEquals(1, accounts.size());
        System.assertEquals('Other', accounts.get(0).Sales_Region__c, 'The account region field returned an unexpected value');
    }
    
    @isTest 
    public static void shouldReturnUnknownForUnknownCountry(){
        final string country = 'UnknownCountry';
        Lead lead = createLeadWithCountry(country);
        insert lead;
        Account account = createAccountWithCountry(country);
        insert account;
        
        List<Lead> leads = [SELECT Id, Sales_Region__c FROM Lead];
        List<Account> accounts = [SELECT Id, Sales_Region__c FROM Account];
        
        System.assertEquals(1, leads.size());
        System.assertEquals('Unknown', leads.get(0).Sales_Region__c, 'The lead region field returned an unexpected value');
        System.assertEquals(1, accounts.size());
        System.assertEquals('Unknown', accounts.get(0).Sales_Region__c, 'The account region field returned an unexpected value');
    }

    @isTest 
    public static void shouldReturnNullForBlankOrNull(){
        final string country = '';
        Lead lead = createLeadWithCountry(country);
        insert lead;
        Account account = createAccountWithCountry(country);
        insert account;
        
        List<Lead> leads = [SELECT Id, Sales_Region__c FROM Lead];
        List<Account> accounts = [SELECT Id, Sales_Region__c FROM Account];
        
        System.assertEquals(1, leads.size());
        System.assertEquals(null, leads.get(0).Sales_Region__c, 'The lead region field returned an unexpected value');
        System.assertEquals(1, accounts.size());
        System.assertEquals(null, accounts.get(0).Sales_Region__c, 'The account region field returned an unexpected value');
    }
}