unpackaged/main/default/objects/Lead/fields/Discovery_notes__c.field-meta.xml
<CustomField>
    <fullName>Discovery_notes__c</fullName>
    <inlineHelpText>Miscellaneous notes that doesn&#39;t fit in the previous categories. Any other information that could be helpful for future reference?</inlineHelpText>
    <label>Discovery notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/How_they_currently_use_Salesforce__c.field-meta.xml
<CustomField>
    <fullName>How_they_currently_use_Salesforce__c</fullName>
    <label>How they currently use Salesforce</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/No_of_people_making_changes_to_SF__c.field-meta.xml
<CustomField>
    <fullName>No_of_people_making_changes_to_SF__c</fullName>
    <inlineHelpText>Number of Salesforce End Users making changes to Salesforce</inlineHelpText>
    <label>Number of people making changes to SF</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/NumberOfSFUsers__c.field-meta.xml
<CustomField>
    <fullName>NumberOfSFUsers__c</fullName>
    <inlineHelpText>This field is required before the lead is converted. If you tried and really cannot get this value please enter -1</inlineHelpText>
    <label>No. of Salesforce end users</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Pains_and_aims__c.field-meta.xml
<CustomField>
    <fullName>Pains_and_aims__c</fullName>
    <inlineHelpText>Why have they started looking at Gearset?</inlineHelpText>
    <label>Pains and aims</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/NumberOfSFUsers__c.field-meta.xml
<CustomField>
    <fullName>NumberOfSFUsers__c</fullName>
    <label>No. of Salesforce end users</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Stakeholder_Summary__c.field-meta.xml
<CustomField>
    <fullName>Stakeholder_Summary__c</fullName>
    <description>A collection of the information gathered while this opportunity was a lead</description>
    <label>SDR Notes</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/classes/TestAddStakeholderSummaryToOpportunity.cls
@isTest
private class TestAddStakeholderSummaryToOpportunity {
    @isTest
    public static void shouldAddStakeholderSummaryToOpportunity() {
        Lead myLead = new Lead(
            LastName = 'Kuiper',
            Company = 'Gearset',
            LeadSource = 'Direct',
            Industry = 'Hi Tech',
            NumberOfEmployees = 70,
            Website = 'gearset.com',
            NumberOfSFUsers__c = 42,
            No_of_people_making_changes_to_SF__c = 10,
            Discovery_Notes__c = 'Test discovery notes',
            How_they_currently_use_Salesforce__c = 'Test how they currently use Salesforce',
            Pains_and_aims__c = 'Test pains and aims'
        );

        insert myLead;

        Database.LeadConvert lc = new Database.LeadConvert();
        lc.setLeadId(myLead.Id);

        lc.setConvertedStatus('Demo Booked');

        Database.LeadConvertResult lcr = Database.convertLead(lc);

        System.assert(lcr.isSuccess());

        Id opportunityId = lcr.getOpportunityId();
        Opportunity opp = [SELECT Stakeholder_Summary__c FROM Opportunity WHERE Id = :opportunityId];

        String summary = opp.Stakeholder_Summary__c;

        System.assert(summary.contains('Test pains and aims'));
    }
}