unpackaged/main/default/objects/Lead/fields/No_of_people_making_changes_to_SF__c.field-meta.xml
<CustomField>
    <fullName>No_of_people_making_changes_to_SF__c</fullName>
    <inlineHelpText>Number of Salesforce End Users making changes to Salesforce</inlineHelpText>
    <label>Number of people making changes to SF</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/NumberOfSFUsers__c.field-meta.xml
<CustomField>
    <fullName>NumberOfSFUsers__c</fullName>
    <inlineHelpText>This field is required before the lead is converted. If you tried and really cannot get this value please enter -1</inlineHelpText>
    <label>No. of Salesforce end users</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Org_Connection__c/Org_Connection__c.object-meta.xml
<CustomObject>
    <label>Org Connection</label>
    <nameField>
        <label>Org Connection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Org Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Org_Connection__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Org Connections</relationshipLabel>
    <relationshipName>Org_Connections</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Org_Connection__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Org Connections</relationshipLabel>
    <relationshipName>Org_Connections</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Org_Connection__c/fields/Org_Username__c.field-meta.xml
<CustomField>
    <fullName>Org_Username__c</fullName>
    <externalId>true</externalId>
    <label>Org Username</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Org_Connection__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/classes/TestUpdateOrgConnectionOnLeadConversion.cls
@isTest
private class TestUpdateOrgConnectionOnLeadConversion {
    @isTest
    public static void shouldAddContactToOrgConnectionOnConversion() {
        Lead myLead = new Lead(
            LastName = 'Kuiper',
            Company = 'Gearset',
            LeadSource = 'Direct',
            Industry = 'Hi Tech',
            NumberOfEmployees = 70,
            Website = 'gearset.com',
            NumberOfSFUsers__c = 42,
            No_of_people_making_changes_to_SF__c = 10
        );

        insert myLead;

        Org_Connection__c oc = new Org_Connection__c(
            Org_Username__c = 'gwilym@gearset.com.dev',
            Phone__c = '01223 333 333',
            Lead__c = myLead.Id
        );

        insert oc;

        Database.LeadConvert lc = new Database.LeadConvert();
        lc.setLeadId(myLead.Id);
        lc.setConvertedStatus('Demo Booked');

        Database.LeadConvertResult lcr = Database.convertLead(lc);

        Id contactId = lcr.getContactId();
        Org_Connection__c newOc = [SELECT Contact__r.Id FROM Org_Connection__c WHERE Id = :oc.Id];

        System.assertEquals(contactId, newOc.Contact__r.Id);
    }
}