unpackaged/main/default/objects/Lead/fields/Sign_In_Country__c.field-meta.xml
<CustomField>
    <fullName>Sign_In_Country__c</fullName>
    <description>The country retrieved from the lead&#39;s IP address when they sign-up. It is set when a user account is first created and updated in the scenario where a user account is updated when logging in to the Gearset app.</description>
    <inlineHelpText>The country retrieved from the lead&#39;s IP address when they sign-up. It is set when a user account is first created and updated in the scenario where a user account is updated when logging in to the Gearset app.</inlineHelpText>
    <label>Sign-In Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unknown</fullName>
                <default>true</default>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Timezone__c.field-meta.xml
<CustomField>
    <fullName>Timezone__c</fullName>
    <label>Timezone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Timezone</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Timezone.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PST</fullName>
    </customValue>
    <customValue>
        <fullName>MST</fullName>
    </customValue>
    <customValue>
        <fullName>CST</fullName>
    </customValue>
    <customValue>
        <fullName>EST</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil Standard Time</fullName>
    </customValue>
    <customValue>
        <fullName>GMT</fullName>
    </customValue>
    <customValue>
        <fullName>CEST</fullName>
    </customValue>
    <customValue>
        <fullName>GST</fullName>
    </customValue>
    <customValue>
        <fullName>IST</fullName>
    </customValue>
    <customValue>
        <fullName>Far East</fullName>
    </customValue>
    <customValue>
        <fullName>AEST</fullName>
    </customValue>
    <customValue>
        <fullName>AWST</fullName>
    </customValue>
    <customValue>
        <fullName>Moscow ST</fullName>
    </customValue>
    <masterLabel>Timezone</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/LeadUpdateController.cls
@RestResource(urlMapping='/LeadUpdate/*')
global without sharing class LeadUpdateController {
	@HttpPatch
    global static void addAdditionalLeadInformation(LeadUpdateInfo additionalInformation) {
        RestRequest request = RestContext.request;
        String leadId = request.requestURI.substring(request.requestURI.lastIndexOf('/') + 1);

        if (isOpportunityId(leadId)) {
            // it is an Opportunity, not a Lead, so there's nothing to do
            return;
        }

        Lead l = [SELECT Id FROM Lead WHERE Id = :leadId];
        
        // Null check will allow us to remove this in the future without breaking anything
        if (additionalInformation.leadQuality != 'Unknown' && additionalInformation.leadQuality != null) {
            l.Rating = additionalInformation.leadQuality;
        }

        if (additionalInformation.timezone != null) {
        	l.Timezone__c = additionalInformation.timezone;
        }
        
        if (additionalInformation.country != null) {
            l.Sign_In_Country__c = additionalInformation.country;
        }
        
        update l;
    } 

    private static boolean isOpportunityId(string recordIdString) {
        Id recordId = Id.valueOf(recordIdString);

        SObjectType recordType = recordId.getSObjectType();

        return recordType.getDescribe().getName() == 'Opportunity';
    }
}