unpackaged/main/default/objects/SubscriptionChurnEvent__c/SubscriptionChurnEvent__c.object-meta.xml
<CustomObject>
    <label>Subscription Churn Event</label>
    <nameField>
        <displayFormat>SC-{00000000}</displayFormat>
        <label>Subscription Churn Event Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Churn Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SubscriptionChurnEvent__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscription Churn Events</relationshipLabel>
    <relationshipName>Subscription_Churn_Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SubscriptionChurnEvent__c/fields/Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The owner of the account at the point of churn.</description>
    <inlineHelpText>The owner of the account at the point of churn.</inlineHelpText>
    <label>Account Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Subscription_Churn_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SubscriptionChurnEvent__c/fields/Date_of_churn__c.field-meta.xml
<CustomField>
    <fullName>Date_of_churn__c</fullName>
    <label>Date of Churn</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/SubscriptionChurnEvent__c/fields/MRR_loss__c.field-meta.xml
<CustomField>
    <fullName>MRR_loss__c</fullName>
    <label>MRR Loss</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/SubscriptionChurnEvent__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/SubscriptionChurnEvent__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Project Ending</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/SetAccountOwnerOnChurnTests.cls
@isTest
private class SetAccountOwnerOnChurnTests {
	@isTest public static void triggerShouldSetChurnAccountOwner() {
		User testUser = TestUtils.createStandardUser('Testman', 'test@test.com');
        insert testUser;
        
        Account a = new Account(OwnerId = testUser.Id, Name = 'Test Account Ltd');
        insert a;
        SubscriptionChurnEvent__c churn = new SubscriptionChurnEvent__c(Account__c = a.Id, Notes__c = 'Note', Date_of_churn__c = Date.newInstance(2021, 05, 20), MRR_loss__c = 1500.00, Type__c = 'Cancelled');
        insert churn;
        
        Test.startTest();
        
        List<SubscriptionChurnEvent__c> churnEvents = [SELECT Id, Notes__c, Account_Owner__c FROM SubscriptionChurnEvent__c];

        Test.stopTest();
        
        System.assertEquals(1, churnEvents.size()); 
        System.assertEquals(churn.Id, churnEvents.get(0).Id, 'Churn Id was not set correctly');
        System.assertEquals(testUser.Id, churnEvents.get(0).Account_Owner__c, 'Account owner was not set correctly');
    }
    
    @isTest public static void triggerShouldSetChurnAccountOwnerWithMultipleInserts() {
		User testUser = TestUtils.createStandardUser('Testman', 'test@test.com');
        insert testUser;
        
        List<Account> accountsToInsert = new List<Account> {
            new Account(OwnerId = testUser.Id, Name = 'Test Account Ltd'),
            new Account(OwnerId = testUser.Id, Name = 'A test account Inc.'),
            new Account(OwnerId = testUser.Id, Name = 'Test services')
        };
        insert accountsToInsert;
        List<SubscriptionChurnEvent__c> churnEventsToInsert = new List<SubscriptionChurnEvent__c> {
            new SubscriptionChurnEvent__c(Account__c = accountsToInsert.get(0).Id, Notes__c = 'Note', Date_of_churn__c = Date.newInstance(2021, 05, 20), MRR_loss__c = 1500.00, Type__c = 'Cancelled'),
            new SubscriptionChurnEvent__c(Account__c = accountsToInsert.get(1).Id, Notes__c = 'Note 2', Date_of_churn__c = Date.newInstance(2021, 04, 20), MRR_loss__c = 1000.00, Type__c = 'Cancelled'),
            new SubscriptionChurnEvent__c(Account__c = accountsToInsert.get(2).Id, Notes__c = 'Note 3', Date_of_churn__c = Date.newInstance(2021, 03, 20), MRR_loss__c = 1200.00, Type__c = 'Cancelled')
        };
        insert churnEventsToInsert;

        Test.startTest();
        
        List<SubscriptionChurnEvent__c> churnEvents = [SELECT Id, Notes__c, Account_Owner__c FROM SubscriptionChurnEvent__c];

        Test.stopTest();
        
        System.assertEquals(3, churnEvents.size());
        for(Integer i = 0; i < churnEvents.size(); i++) {
            System.assertEquals(churnEventsToInsert.get(i).Id, churnEvents.get(i).Id, 'Churn Id was not set correctly');
        	System.assertEquals(testUser.Id, churnEvents.get(i).Account_Owner__c, 'Account owner was not set correctly');
        }
    }
}