unpackaged/main/default/objects/Case/fields/Current_Workaround__c.field-meta.xml
<CustomField>
    <fullName>Current_Workaround__c</fullName>
    <inlineHelpText>What is your current workaround?</inlineHelpText>
    <label>Current Workaround</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Gearset_Team__c.field-meta.xml
<CustomField>
    <fullName>Gearset_Team__c</fullName>
    <inlineHelpText>What team are you in?</inlineHelpText>
    <label>Gearset Team</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Gearset_Departments</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Stakeholder__c.field-meta.xml
<CustomField>
    <fullName>Stakeholder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The user who requested this case</inlineHelpText>
    <label>Stakeholder</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Stakeholder</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/What_is_the_problem__c.field-meta.xml
<CustomField>
    <fullName>What_is_the_problem__c</fullName>
    <inlineHelpText>What is the problem you are trying to solve?</inlineHelpText>
    <label>What is the problem?</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Gearset_Team__c/Gearset_Team__c.object-meta.xml
<CustomObject>
    <label>Gearset Team</label>
    <nameField>
        <label>Gearset Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gearset Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/globalValueSets/Gearset_Departments.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sales</fullName>
        <default>true</default>
        <label>Sales</label>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Success</fullName>
    </customValue>
    <customValue>
        <fullName>Alliances</fullName>
    </customValue>
    <customValue>
        <fullName>Operations</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering</fullName>
    </customValue>
    <customValue>
        <fullName>DevOps</fullName>
    </customValue>
    <customValue>
        <fullName>People</fullName>
    </customValue>
    <masterLabel>Gearset Departments</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CaseTest.cls
@isTest
public class CaseTest {
    private static User gearbot = [SELECT Id FROM User WHERE Username LIKE 'gearbot@gearset.com%'];

    @isTest
    static void shouldAssignCurrentUserAsStakeholderIfNewCaseHasNoStakeholder() {
        Case newCase = getTestCase();

        insert newCase;

        Case insertedCase = [SELECT Stakeholder__c FROM Case WHERE Id = :newCase.Id];
        System.assertEquals(UserInfo.getUserId(), insertedCase.Stakeholder__c);
    }

    @isTest
    static void shouldNotAssignCurrentUserAsStakeholderIfNewCaseHasStakeholder() {
        Case newCase = getTestCase();
        newCase.Stakeholder__c = gearbot.Id;

        insert newCase;

        Case insertedCase = [SELECT Stakeholder__c FROM Case WHERE Id = :newCase.Id];
        System.assertEquals(gearbot.Id, insertedCase.Stakeholder__c);
    }

    private static Case getTestCase() {
        Case newCase = new Case();
        newCase.Gearset_Team__c = 'Sales';
        newCase.Type = 'Problem';
        newCase.What_is_the_problem__c = 'n/a';
        newCase.Current_Workaround__c = 'n/a';
        newCase.Subject = 'n/a';
        newCase.Description = 'n/a';

        return newCase;
    }
}