unpackaged/main/default/objects/Gearset_Team__c/Gearset_Team__c.object-meta.xml
<CustomObject>
    <label>Gearset Team</label>
    <nameField>
        <label>Gearset Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gearset Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Gearset_Team__c/fields/Gearset_Team_Id__c.field-meta.xml
<CustomField>
    <fullName>Gearset_Team_Id__c</fullName>
    <externalId>true</externalId>
    <label>Gearset Team Id</label>
    <description>The id of the Gearset team, as you might find on the admin site.</description>
    <inlineHelpText>The id of the Gearset team, as you might find on the admin site.</inlineHelpText>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Rating__c/Rating__c.object-meta.xml
<CustomObject>
    <description>An internal Gearset rating</description>
    <label>Rating</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Rating Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ratings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Rating__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Rating__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Rating__c/fields/Gearset_Team__c.field-meta.xml
<CustomField>
    <fullName>Gearset_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Gearset Team</label>
    <referenceTo>Gearset_Team__c</referenceTo>
    <relationshipLabel>Ratings</relationshipLabel>
    <relationshipName>Ratings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Rating__c/fields/Rating_Id__c.field-meta.xml
<CustomField>
    <fullName>Rating_Id__c</fullName>
    <externalId>true</externalId>
    <label>Rating Id</label>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Rating__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <label>Score</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Rating_Submitted__e/Rating_Submitted__e.object-meta.xml
<CustomObject>
    <label>Rating Submitted</label>
    <pluralLabel>Ratings Submitted</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Rating_Submitted__e/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Rating_Submitted__e/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <length>26</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Rating_Submitted__e/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Rating_Submitted__e/fields/Rating_Id__c.field-meta.xml
<CustomField>
    <fullName>Rating_Id__c</fullName>
    <label>Rating Id</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Rating_Submitted__e/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <label>Score</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Rating_Submitted__e/fields/Team_Id__c.field-meta.xml
<CustomField>
    <fullName>Team_Id__c</fullName>
    <label>Team_Id</label>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/NewRatingTriggerTests.cls
@isTest
private class NewRatingTriggerTests {
	@isTest public static void ratingEventTriggerShouldPopulateDatabase() {
        Gearset_Team__c team = new Gearset_Team__c(Gearset_Team_Id__c = '13219ec0-3a81-44c5-a300-de14b7d0235f');
        Rating_Submitted__e event = new Rating_Submitted__e(Rating_Id__c = 'Rating 1', Team_Id__c = team.Gearset_Team_Id__c, Email__c = 'test1@test.com', Comment__c = 'Comment 1', Score__c = 8, Date__c = '2021-01-18T18:11:09.256Z');
        
        Test.startTest();
        
        insert team;
        Database.SaveResult sr = EventBus.publish(event);
            
        Test.stopTest();
                
        System.assertEquals(true, sr.isSuccess());
        
        List<Rating__c> ratings = [SELECT Id FROM Rating__c];

        System.assertEquals(1, ratings.size()); 
    }
}