unpackaged/main/default/objects/zoom_app__Zoom_Webinar_Attendee__c/zoom_app__Zoom_Webinar_Attendee__c.object-meta.xml
<CustomObject>
    <label>Zoom Webinar Attendee</label>
    <nameField>
        <displayFormat>Webinar-Att-{0000}</displayFormat>
        <label>Zoom Webinar Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zoom Webinar Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/zoom_app__Zoom_Webinar_Attendee__c/fields/zoom_app__Name__c.field-meta.xml
<CustomField>
    <fullName>zoom_app__Name__c</fullName>
    <label>Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/zoom_app__Zoom_Webinar_Attendee__c/fields/zoom_app__User_Email__c.field-meta.xml
<CustomField>
    <fullName>zoom_app__User_Email__c</fullName>
    <label>User Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/classes/NewZoomWebinarAttendeeTriggerTests.cls
@isTest
private class NewZoomWebinarAttendeeTriggerTests {
	@isTest public static void newZoomWebinarAttendeeTriggerShouldCreateLeads() {
        List<zoom_app__Zoom_Webinar_Attendee__c> newAttendees = new List<zoom_app__Zoom_Webinar_Attendee__c>{
            new zoom_app__Zoom_Webinar_Attendee__c (
        	zoom_app__User_Email__c = 'testwebinarlead@gearset.com',
        	zoom_app__Name__c = 'Test'
            ),
            new zoom_app__Zoom_Webinar_Attendee__c (
                zoom_app__User_Email__c = 'testwebinarlead1@gearset.com',
                zoom_app__Name__c = 'Another Test'
            )
        };

        insert newAttendees;

        List<Lead> leads = [SELECT Id FROM Lead];
        System.assertEquals(2, leads.size());
    }
}